---
title: "Figure 5"
---

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(Seurat)
library(tidyverse)
library(ggrepel)
library(ggpubr)
library(readxl)

sc<-readRDS("data/fixed_annotated_aux.seurat.rds")
sc<-subset(sc,cells = which(sc$Class=="Peritoneal endometriosis"&
              str_detect(sc$harmonized_major_plus_immune_cell_type,"^Ex|Ery",negate = T)))
gc()
sc$has_LA<-ifelse(sc$LA_per_Sample>0,"LA+","LA-")
sc@meta.data<-sc@meta.data%>%
  mutate(nosub=str_remove(harmonized_major_plus_immune_cell_type," \\(.+"))%>%
  mutate(nosub=str_replace(nosub,"Memmo","Memo")%>%str_remove("Early "))

temp<-read_csv("data/myeloid_subgroups.csv")
aux_table<-sc@meta.data%>%rownames_to_column("barcode")
aux_table<-temp%>%select(barcode,myeloid_cl)%>%
    right_join(aux_table)%>%
    mutate(nosub=ifelse(!is.na(myeloid_cl),
                        myeloid_cl,nosub))%>%
    select(-myeloid_cl)
aux_table<-aux_table[order(match(aux_table$barcode,colnames(sc))),]
sc<-AddMetaData(sc,metadata = aux_table,col.name = "nosub")

```

## sc FC
```{r echo=TRUE, message=FALSE, warning=FALSE}
deg<-data.table::fread("docs/hasLA_DEG_sc_newMyeloid_MAST.gz")

temp<-deg%>%filter(ct=="EnS cells")%>%
  mutate(STATUS=case_when(avg_log2FC<=-1&p_val_adj<0.05~"Low",
                          avg_log2FC>=1&p_val_adj<0.05~"Up",
                          TRUE~"Not.Sig"))
#min(temp$p_val_adj[temp$p_val_adj>0])
temp<-temp%>%mutate(p_pos=p_val_adj+p_val_adj+1e-309)
temp%>%ggplot(aes(x=avg_log2FC,y=-log10(p_pos),col=STATUS))+
    geom_point(size=.5)+geom_text_repel(data=temp%>%filter(STATUS!="Not.Sig")
                                 %>%group_by(STATUS)%>%
                                     slice_min(p_pos,n = 5),
                                 aes(label=gene),size=3,show.legend = F)+
    theme_classic()+theme(panel.grid = element_blank(),legend.position = "bottom")+
    scale_color_manual(values = c("#2166ac", "grey", "#b2182b"))+
  geom_vline(xintercept = 1,linetype="dotted")+
  geom_vline(xintercept = -1,linetype="dotted")+
  guides(col=guide_legend(override.aes = list(size=3)))+
  labs(x="LFC",y="-log10(P.adj)")   

temp<-DotPlot(sc,features = "ARID5B",group.by = "nosub",split.by = "has_LA")
temp$data%>%separate(id,into = c("ct","has_LA"),sep = "_")%>%
  filter(ct!="Myeloid cells")%>%arrange(desc(avg.exp))%>%
  mutate(ct=factor(ct,levels=unique(ct)))%>%
  ggplot(aes(x=has_LA,y=ct,col=avg.exp,size=pct.exp))+
  geom_point()+scale_color_viridis_c(option = 'B',direction = -1)+
  theme_classic()+labs(x="",y="",col="Avg.Exp",size="%")

```

# Menstrual cycle
```{r echo=TRUE, message=FALSE, warning=FALSE}
bulk<-read_csv("data/TMM_normalised_endometrial_expression_ARID5B_IGFBP5_FOXO1.csv")
bulk<-bulk%>%
  mutate(Stage=case_when(Stage.of.Cycle==1~"Menstrual",
                                  Stage.of.Cycle==2~"Early-proliferative",
                                  Stage.of.Cycle==3~"Mid-proliferative",
                                  Stage.of.Cycle==4~"Late-proliferative",
                                  Stage.of.Cycle==5~"Early-secretory",
                                  Stage.of.Cycle==6~"Mid-secretory",
                                  Stage.of.Cycle==7~"Late-secretory"))%>%
  arrange(Stage.of.Cycle)%>%
  mutate(Stage=factor(Stage,levels=unique(Stage)))
bulk%>%ggplot(aes(x=Stage,y=ARID5B_CPM))+
  geom_boxplot()+theme_classic()+labs(x="Stage of cycle",y="ARID5B (CPM)")+
  theme(axis.text.x = element_text(angle=45,vjust =1,hjust = 1))

```

# ARID5B IPSC (script/ARID5B_MME.R)
```{r echo=TRUE, message=FALSE, warning=FALSE}
raw_data <- read_excel("data/paper_figure.xlsx",
                       sheet = "Main figure data")
timepoint_order <- c("iPSC", "D0", "D4", "D8", "D12", "D20", "D28")
available_timepoints <- timepoint_order[timepoint_order %in% colnames(raw_data)]
gene_order <- c("ARID5B", "MME")
plot_data <- raw_data %>%
  filter(Gene %in% gene_order) %>%
  pivot_longer(cols = all_of(available_timepoints),
    names_to = "Timepoint",
    values_to = "FoldChange") %>%
  mutate(Gene = factor(Gene,
      levels = gene_order),
    Timepoint = factor(Timepoint,
      levels = available_timepoints))
summary_data <- plot_data %>%
  group_by(Gene, Timepoint) %>%
  summarise(Mean = mean(FoldChange, na.rm = TRUE),
    SD = sd(FoldChange, na.rm = TRUE),
    .groups = "drop")

ggplot() +
  geom_col(data = summary_data,
    aes(x = Timepoint, y = Mean),
    width = 0.70,
    fill = NA,
    color = "black",
    linewidth = 0.65) +
  geom_errorbar(data = summary_data,
    aes( x = Timepoint, ymin = pmax(Mean - SD, 0),ymax = Mean + SD),
    width = 0.18,
    linewidth = 0.60,
    color = "black") +
  geom_point(data = plot_data,
    aes(x = Timepoint,y = FoldChange),
    position = position_jitter( width = 0.10,height = 0,seed = 123),
    shape = 21,
    size = 2.7,
    stroke = 0.65,
    fill = scales::alpha("#6B8E23", 0.5),
    color = "black") +
  facet_wrap(vars(Gene),ncol = 1,scales = "free_y") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  labs(x = NULL,y = "Fold change relative to iPSC") +
  theme_classic(base_size = 11) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_text(color = "black",margin = margin(r = 12)),
      axis.text = element_text(color = "black"),
      axis.text.x = element_text(angle = 45,hjust = 1,vjust = 1),
      axis.line.x = element_line(linewidth = 0.65,color = "black"),
      axis.line.y = element_line(linewidth = 0.65,color = "black"),
      axis.ticks = element_line(linewidth = 0.50,color = "black"),
      strip.background = element_blank(),
      strip.text = element_text(face = "italic",color = "black"),
      panel.spacing = grid::unit(1.3,"lines"))
```

# ARID5B KD (script/ARID5B_KD.R)
```{r echo=TRUE, message=FALSE, warning=FALSE}
gsea_summary<-read_csv("data/All_Contrasts_Hallmark_GSEA_Summary_filtered.csv")
i<-gsea_summary %>%
    filter(!is.na(NES), !is.na(p.adjust)) %>%
    mutate(pass = abs(NES) >= 1.5 & p.adjust < 0.05) %>%
    filter(pass) %>%
    group_by(Treatment, pathway) %>%
    summarise(n_pass      = n_distinct(Timepoint),
              max_abs_NES = max(abs(NES)),
              direction   = ifelse(NES[which.max(abs(NES))] >= 0, "Up", "Down"),
              .groups = "drop") %>%
    filter(n_pass >= 2) %>% group_by(Treatment) %>%
        slice_max(order_by = max_abs_NES, n = 10) 
gsea_summary%>%filter(pathway%in%i$pathway)%>%
  mutate(Treatment=factor(Treatment,levels=c("Basal", "E2", "MPA", "cAMP")))%>%
  ggplot(aes(x=Timepoint,y=pathway,col=NES,size=p.adjust))+geom_point()+
  facet_wrap(~Treatment,ncol=4)+theme_classic()+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1),
        strip.background = element_blank())+
  scale_color_gradient2(low="#2166ac",mid="#f7f7f7",high = "#b2182b")+
  scale_size(range=c(5,1),trans = "sqrt",breaks = c(1e-7,1e-5,1e-2,1))+labs(size="Padj")

treatments<-c("Basal", "E2", "MPA", "cAMP")
timepoints<-c("72h", "96h", "120h", "192h")
file<-"data/siARID5B_vs_NTC_all_contrasts_limma_voom_filtered.xlsx"
contrast_sheets <- readxl::excel_sheets(file)
parse_contrast <- function(sheet_name) {
  parts <- strsplit(sheet_name, "_")[[1]]
  n <- length(parts)
  list(Treatment = parts[n - 1], Timepoint = parts[n])
}
all_filtered_res <- map_dfr(contrast_sheets, function(sheet_name) {
  parsed <- parse_contrast(sheet_name)
  readxl::read_excel(file, sheet = sheet_name) %>%
    mutate(Contrast  = sheet_name,
           Treatment = parsed$Treatment,
           Timepoint = parsed$Timepoint)}) %>%
  mutate(Treatment = factor(Treatment, levels = treatments),
         Timepoint = factor(Timepoint, levels = timepoints))
gene_sets <- list(
  #"TGF-\u03B2 Signaling" = c("TGFBR1", "CDKN1C", "SMAD3", "SERPINE1", "ID2", "ID3"),
  "Decidualization" = c("HOXA10", "PRL", "IGFBP1", "LEFTY2", "FOXO1", "WNT4", "HSD11B1","PGR"),
  "Cholesterol" = c("ACAT2", "CD9", "ALCAM","SREBF2", "HMGCR", "HMGCS1", "MVD"), #1 from basal, 1 from MPA, 1 from cAMP
  "Angiogenesis" = c("POSTN", "SPP1","LUM"), #1 from basal, 1 from E2, 1 from MPA
  "E2F targets / proliferation" = c("E2F8", "DLGAP5", "BIRC5","CDC20"), #1 from basal, cAMP, 1 from E2, 1 from MPA
  "Epithelial-mesenchymal transition" = c("MGP", "SERPINE2","COL11A1"), # 1 from each treatment
  "TNFA-NFKB" = c("BHLHE40", "PLAU"), #1 from MPA, 1 from cAMP
  "IL-6/JAK-STAT3 signaling" = c("CD14", "SOCS3", "ITGB3","SOCS1"), # 3 from cAMP
  "TNF superfamily ligands" = c("TNFSF4", "TNFSF18")
)
temp<-all_filtered_res%>%filter(SYMBOL%in%unlist(gene_sets))
gene_sets<-lapply(names(gene_sets), function(x) 
  as.data.frame(cbind(SYMBOL=gene_sets[[x]],set=x)))%>%bind_rows()
temp<-temp%>%left_join(gene_sets)
temp%>%mutate(Timepoint=factor(Timepoint,levels=timepoints),
              Treatment=factor(Treatment,levels=treatments))%>%
  ggplot(aes(x=SYMBOL,y=Timepoint,col=logFC,size=adj.P.Val))+geom_point()+
  facet_grid(rows=vars(Treatment),cols=vars(set),
             scales="free",space="free")+theme_classic()+
    theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1),
          strip.background = element_blank())+
    scale_color_gradient2(low="#2166ac",mid="#f7f7f7",high = "#b2182b",
                          oob=scales::squish,limits=c(-3,3))+
  scale_size(range=c(5,1),trans="sqrt",breaks = c(1e-16,1e-8,1e-4))+
  labs(x="",size="Padj",col="LFC")
```

# TNFRSF18
```{r echo=TRUE, message=FALSE, warning=FALSE}
tnk<-subset(sc,cells = which(str_detect(sc$nosub,"T-|NK")))
temp<-DotPlot(tnk,features = c("TNFRSF18","TNFRSF4"),group.by = "nosub",split.by = "has_LA")
temp<-temp$data%>%separate(id,into=c("ct","has_LA"),sep = "_")

temp%>%filter(ct!="Myeloid cells")%>%arrange(desc(avg.exp))%>%
    mutate(ct=factor(ct,levels=unique(ct)))%>%
    ggplot(aes(x=has_LA,y=ct,col=avg.exp,size=pct.exp))+
    geom_point()+scale_color_viridis_c(option = 'B',direction = -1)+
    theme_classic()+labs(x="",y="",col="Avg.Exp",size="%")+
  facet_grid(~features.plot)+theme(strip.background = element_blank())

```

# GITR in cosmx
```{r echo=TRUE, message=FALSE, warning=FALSE}

files<-list.files()
files<-files[str_detect(files,"bg")][-1]#no endometrioma
metadata<-lapply(files,vroom::vroom)%>%bind_rows()
gc()
metadata<-metadata%>%filter(str_detect(fov_type,"CD|NK"))
mat<-vroom::vroom("endometrium.csv")%>%filter(cell_ID%in%metadata$cell_ID)
mat<-vroom::vroom("PE.csv")%>%filter(cell_ID%in%metadata$cell_ID)%>%bind_rows(mat)
gc()    

mat<-mat%>%column_to_rownames("cell_ID")%>%t()
negavg<-colMeans(mat[c("Ms IgG1","Rb IgG"),])
normi<-t(t(mat)-negavg)
normi<-asinh(normi/5)
nobatch<-sva::ComBat(dat = normi,batch = str_remove(colnames(normi),"c_1.+"),
                     BPPARAM = BiocParallel::MulticoreParam(workers = 2))

temp<-metadata%>%select(cell_ID,dom_nEndoh1_75,Class,fov_type)
temp<-nobatch%>%t()%>%as.data.frame()%>%
  rownames_to_column("cell_ID")%>%select(cell_ID,GITR)%>%
  inner_join(temp)
temp<-temp%>%mutate(index=case_when(dom_nEndoh1_75==6~1,
                                    dom_nEndoh1_75==3~2,
                                    dom_nEndoh1_75==4~3,
                                    dom_nEndoh1_75==2~4,
                                    dom_nEndoh1_75==1~6,
                                    TRUE~dom_nEndoh1_75))#as defined in Fig2

domcol <- c( "gray13", "gold2", "lightskyblue2", "darkorange1", "plum4", "maroon")
names(domcol)<-6:1
temp%>%filter(dom_nEndoh1_75!=7)%>%mutate(Run_Tissue_name=str_remove(cell_ID,"c_.+"))%>%
    group_by(Run_Tissue_name,index,fov_type)%>%summarise(GITR=mean(GITR))%>%
    ggplot(aes(x=as.factor(index),y=GITR,col=as.factor(index)))+
    geom_violin()+geom_boxplot(width=.1)+
    labs(x="Domain",y="Average GITR")+theme_classic()+
    stat_compare_means(label="p.signif",ref.group = 1)+
    scale_color_manual(values=domcol)+facet_wrap(~fov_type,nrow=3)+
    theme(legend.position = "n",strip.background = element_blank())

```

