---
title: "Dataset introduction"
---


```{r}
library(tidyverse)
library(cowplot)
library(ggplot2)
library(ComplexHeatmap)
library(circlize)
library(ggpubr)
library(ggnewscale)

files<-list.files()
files<-files[str_detect(files,"bgclus")]
files<-files[-1]
metadata<-lapply(files,data.table::fread)%>%bind_rows()

domcol <- c( "gray13", "gold2", "plum4", "darkorange1", "lightskyblue2", "firebrick", "burlywood3", "gray51", "springgreen4", "lightpink2", "deepskyblue4", "lightsalmon2", "mediumpurple4", "orange", "maroon", "yellow3", "brown4", "yellow4", "sienna4", "chocolate")
names(domcol)<-1:20
slidecol<-sample(domcol,length(unique(metadata$Run_Tissue_name)))
names(slidecol)<-unique(metadata$Run_Tissue_name)
classcols = c( "Eutopic endometrium" = "#c2a5cf", 
              "Peritoneal endometriosis" = "#d9f0d3")
cellcols<-c("#8DB600","#fdae61","#a95f96","#0067A5","#604E97",
            "#f46d43","hotpink","#BE0032","cornflowerblue","black")
names(cellcols)<-c("B cells","Plasma cells","CD4 T cells","CD8 T cells",
                   "NK cells","Myeloid cells","unknown","Epithelial","Stroma","low_signal")

```
# Filter/QC
```{r}
temp<-metadata%>%group_by(Run_Tissue_name)%>%
  summarise(thres=quantile(nCount_RNA,c(0.05)))
metadata<-metadata%>%left_join(temp)
metadata<-metadata%>%
  mutate(qc_type=ifelse(nCount_RNA>thres,
                        cl_corrected,"low_signal"))

temp<-metadata%>%count(Run_Tissue_name,fov,qc_type)%>%
  group_by(Run_Tissue_name,fov)%>%mutate(prop=100*n/sum(n))%>%
  filter(qc_type=="low_signal")
i<-temp%>%filter(prop>=25)%>%select(1:3)
colnames(i)[3]<-"fov_type"
metadata<-metadata%>%left_join(i)
metadata<-metadata%>%
  mutate(fov_type=ifelse(is.na(fov_type),qc_type,fov_type))%>%
  select(-qc_type)

metadata<-metadata%>%filter(!fov_type%in%c("low_signal","unknown"))
```
# Cell type markers
```{r}
markers<-read_tsv("cosmx_markers.tsv")
markers<-markers%>%separate_rows(Positive,sep = ",")%>%
  distinct(Positive)%>%unlist()
markers<-markers[c(2,1,5,4,8,7,9,12,10,16,18,3,19,22,23)]

pe<-vroom::vroom("/media/Lawrenson_Lab_NAS/uthscsa/group_data/CosMx_temp/PE.csv")%>%
  filter(cell_ID%in%metadata$cell_ID)
mat<-vroom::vroom("/media/Lawrenson_Lab_NAS/uthscsa/group_data/CosMx_temp/endometrium.csv")%>%filter(cell_ID%in%metadata$cell_ID)
mat<-mat%>%bind_rows(pe)%>%column_to_rownames("cell_ID")%>%t()
negavg<-colMeans(mat[c("Ms IgG1","Rb IgG"),])
normi<-t(t(mat)-negavg)
normi<-asinh(mat/5)
normi<-sva::ComBat(dat = normi,batch = str_remove(colnames(normi),"c_.+"),
                     BPPARAM = BiocParallel::MulticoreParam(workers = 10))

temp<-metadata%>%select(cell_ID,fov_type)
avged<-split(temp,by = "fov_type")%>%
  sapply(function(x) rowMeans(normi[,x$cell_ID]))

pC<-avged%>%t()%>%scale()%>%t()%>%as.data.frame()%>%
    rownames_to_column("probe")%>%filter(probe%in%markers)%>%
    pivot_longer(-probe,names_to = "celltype",values_to = "z")%>%
    filter(celltype!="unknown")%>%
    group_by(celltype)%>%
    mutate(maxz=z/max(abs(z)),
           probe=factor(probe,levels=markers),
           celltype=factor(celltype,levels=names(cellcols)))%>%
    ungroup()%>%
    ggplot(aes(x=probe,y=celltype,fill=maxz))+geom_tile()+
    #scale_fill_gradient2(low = "blue",mid = "white",high = "red")+
    scale_fill_viridis_c(option = "D",direction = -1)+
    theme_minimal()+
    theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))

pC1<-temp%>%count(fov_type)%>%
  mutate(fov_type=factor(fov_type,levels = names(cellcols)))%>%
  ggplot(aes(x=n,y=fov_type))+geom_col()+theme_classic()+scale_x_log10()+
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        panel.spacing = unit(.01, "lines"),
        plot.margin=grid::unit(c(0,0,0,-5),"mm"),
        axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))+
  labs(x="Cells",y="")
plot_grid(pC+theme(legend.position = "left"),pC1,
          align = 'h',axis = "tb",rel_widths = c(.6,.4))

```

#   Cell composition contrast
```{r}
library(limma)
library(speckle)

temp<-metadata%>%distinct(Class,Run_Tissue_name)
props<-getTransformedProps(metadata$fov_type,
                           metadata$Run_Tissue_name)
props<-props$TransformedProps[,temp$Run_Tissue_name]
designM<-model.matrix(~0+Class,data=temp)#groups around replicates=samplename
colnames(designM)<-str_replace(colnames(designM)," ","_")
fit<-lmFit(props,designM)
cont<-makeContrasts(ClassPeritoneal_endometriosis-ClassEutopic_endometrium,levels = designM)
fit<-contrasts.fit(fit,cont)
fit <- eBayes(fit, robust=TRUE)
res<-topTable(fit,number = nrow(props),coef = 1)
res<-res%>%rownames_to_column("cell_type")

## scRNA
library(Seurat)

sc<-readRDS("data/fixed_annotated_aux.seurat.rds")
sc<-subset(sc,cells = which(sc$Class%in%c("Eutopic endometrium","Peritoneal endometriosis")&
                            str_detect(sc$harmonized_major_plus_immune_cell_type,
                                 "^Ex|Ery",negate=T)))
#fix labels
sc@meta.data<-sc@meta.data%>%
  mutate(celltype=case_when(str_detect(harmonized_major_cell_type,"Epi|Meso")~"Epithelial",
                            str_detect(harmonized_major_plus_immune_cell_type,"CD8|Gamma")~"CD8 T cells",
                            str_detect(harmonized_major_plus_immune_cell_type,"Th.+ T-cells")~"CD4 T cells",
                            str_detect(harmonized_major_cell_type,"EnS|Smooth|Mesen|Endot")~"Stroma",
                            TRUE~harmonized_major_cell_type))
sc@meta.data<-sc@meta.data%>%
  mutate(nosub=str_remove(harmonized_major_plus_immune_cell_type," \\(.+"))%>%
  mutate(nosub=str_replace(nosub,"Memmo","Memo")%>%str_remove("Early "))
temp<-read_csv("data/myeloid_subgroups.csv")
aux_table<-sc@meta.data%>%rownames_to_column("barcode")
aux_table<-temp%>%select(barcode,myeloid_cl)%>%
  right_join(aux_table)%>%
  mutate(nosub=ifelse(!is.na(myeloid_cl),
                      myeloid_cl,nosub))%>%
  select(-myeloid_cl)

temp<-aux_table%>%distinct(Class,SampleName)
props<-getTransformedProps(aux_table$celltype,
                           aux_table$SampleName)
props<-props$TransformedProps[,temp$SampleName]
designM<-model.matrix(~0+Class,data=temp)#groups around replicates=samplename
colnames(designM)<-str_replace(colnames(designM)," ","_")

fit<-lmFit(props,designM)
cont<-makeContrasts(ClassPeritoneal_endometriosis-ClassEutopic_endometrium,levels = designM)
fit<-contrasts.fit(fit,cont)
fit <- eBayes(fit, robust=TRUE)
resc<-topTable(fit,number = nrow(props),coef = 1)
resc<-resc%>%rownames_to_column("cell_type")

temp<-res%>%mutate(CosMx_LFC=logFC,
                   CosMx_P=adj.P.Val)%>%
  select(cell_type,CosMx_LFC,CosMx_P)
temp<-resc%>%mutate(RNA_LFC=logFC,RNA_P=adj.P.Val)%>%
  select(cell_type,RNA_LFC,RNA_P)%>%inner_join(temp)
temp$max_P<-apply(temp[,c(3,5)],1,max)
pE<-temp%>%ggplot(aes(x=RNA_LFC,y=CosMx_LFC,size=max_P))+
  geom_point()+geom_text_repel(aes(label=cell_type))+
  scale_size(range=c(6,3),breaks = c(0,.05,.5,1))+
  theme_linedraw()+geom_vline(xintercept = 0)+
  geom_hline(yintercept = 0)+
  labs(x="RNA LFC",y="protein LFC",size="Max. P.")+
  theme(legend.position = "bottom",panel.grid = element_blank())

temp<-metadata%>%count(Class,fov_type,name = "CosMx_n")%>%
  mutate(celltype=fov_type)%>%select(-fov_type)
temp<-aux%>%count(Class,celltype,name = "RNA_n")%>%inner_join(temp)%>%
  pivot_longer(RNA_n:CosMx_n,names_to = "platform",values_to = "n")
temp<-temp%>%group_by(Class,platform)%>%
  summarise(n=sum(n),celltype="Total")%>%bind_rows(temp)
pE1<-temp%>%mutate(celltype=factor(celltype,
  levels=c(names(cellcols)[c(1,2,4,3,8,9,6,5)],"Total")))%>%
  ggplot(aes(x=n,y=celltype,fill=Class))+
  geom_bar(stat="identity",position = "fill")+
  facet_grid(~platform)+scale_fill_manual(values=classcols)+
  theme_classic()+theme(strip.background = element_blank(),
                        legend.position = "bottom")+
  labs(x="Proportion")
plot_grid(pE,pE1,rel_widths = c(.4,.6))
```
# RNA difference
```{r}
alt_cellcols<-CellChat::scPalette(length(unique(aux_table$nosub)))
#alt_cellcols<-grDevices::colorRampPalette(alt_cellcols)(30)
names(alt_cellcols)<-sort(unique(aux_table$nosub))
alt_cellcols["B-cells"]<-cellcols["B cells"]
alt_cellcols["Plasmablast/Plasma cells"]<-cellcols["Plasma cells"]

temp<-aux_table%>%distinct(Class,SampleName)
props<-getTransformedProps(aux_table$celltype,
                           aux_table$SampleName)
props<-props$TransformedProps[,temp$SampleName]
designM<-model.matrix(~0+Class,data=temp)#groups around replicates=samplename
colnames(designM)<-str_replace(colnames(designM)," ","_")
fit<-lmFit(props,designM)
cont<-makeContrasts(ClassPeritoneal_endometriosis-ClassEutopic_endometrium,levels = designM)
fit<-contrasts.fit(fit,cont)
fit <- eBayes(fit, robust=TRUE)
resc<-topTable(fit,number = nrow(props),coef = 1)
resc<-resc%>%rownames_to_column("cell_type")
resc<-resc%>%arrange(logFC)%>%
  mutate(cell_type=factor(cell_type,levels = cell_type))

pF<-resc%>%filter(cell_type!="Myeloid cells")%>%
  mutate(Class=ifelse(logFC>0,"Peritoneal endometriosis",
                               "Eutopic endometrium"))%>%
  ggplot(aes(x=logFC,y=cell_type,col=Class))+
  geom_point(aes(size=adj.P.Val))+
  geom_segment(aes(xend=0))+
  geom_vline(xintercept = 0)+
  scale_color_manual(values=classcols)+theme_classic()+
  theme(axis.line.y = element_blank(),axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        plot.margin=grid::unit(c(0,0,0,-4), "mm"))+
  scale_size(range=c(5,1),trans="log10",breaks = c(1e-5,1e-3,1e-1))

temp<-aux_table%>%
  filter(nosub!="Myeloid cells")%>%count(nosub)%>%
  mutate(nosub=factor(nosub,levels=levels(pF$data$cell_type)))
pF0<-temp%>%ggplot(aes(x=n,y=nosub,fill=nosub))+geom_col()+
  scale_fill_manual(values=alt_cellcols)+theme_classic()+
  theme(legend.position = "n")+
  labs(x="Total cells",y="Cell type")+scale_x_log10()
```
## Subsets 
```{r}
tcells<-subset(sc,cells=which(str_detect(sc$celltype,"T cells")))
tcells<-RunUMAP(tcells,repulsion.strength = 5,dims = 1:15)
tcoords<-tcells@reductions$umap@cell.embeddings%>%as.data.frame()%>%
  rownames_to_column("barcode")
tcoords%>%write_csv("RNA_Tcells_umap.csv")
nont<-subset(sc,cells = which(str_detect(sc$celltype,"B|Mast|NK|Plas|My")))
nont<-RunUMAP(nont,dims = 1:15)
nontcoords<-nont@reductions$umap@cell.embeddings%>%
  as.data.frame()%>%rownames_to_column("barcode")
nontcoors%>%write_csv("RNA_nonTcells_umap.csv")
sc<-subset(sc,subset=celltype%in%c("Stroma","Epithelial"))
sc<-RunUMAP(sc,dims = 1:15)
nonimmcoords<-sc@reductions$umap@cell.embeddings%>%
  as.data.frame()%>%rownames_to_column("barcode")
nonimmcoords%>%data.table::fwrite("RNA_nonImmune_umap.csv")
coords<-tcoords%>%mutate(ct="T-cells")%>%
  bind_rows(nonimmcoords%>%mutate(ct="non Immune"))%>%
  bind_rows(nontcoords%>%mutate(ct="non T-cells"))
coords<-aux_table%>%select(barcode,nosub,Class)%>%
  right_join(coords)
temp<-coords%>%group_by(nosub,ct)%>%
  summarise(center1=median(umap_1),
            center2=median(umap_2))

pF1<-coords%>%filter(nosub!="Myeloid cells"&!is.na(nosub))%>%
    ggplot(aes(x=umap_1,y=umap_2,col=nosub))+
    geom_point(size=.1)+
    geom_text_repel(data=temp,
                    aes(x=center1,y=center2,label=nosub),
                    col="black")+
    scale_color_manual(values=alt_cellcols)+
    facet_grid(~ct)+theme_light()+
    theme(strip.background = element_blank(),axis.text.x = element_blank(),
          legend.position = "n",panel.grid = element_blank())+
    labs(x="")

pF2<-pF1$data %>%
    filter(nosub != "Myeloid cells" & !is.na(nosub)) %>%
    ggplot(aes(x = umap_1, y = umap_2)) +
    geom_point(aes(col = nosub), size = .1,alpha=.1) +
    scale_color_manual(values = alt_cellcols) +
    new_scale_color() +
    stat_density_2d(
        data = pF1$data %>%
            filter(nosub != "Myeloid cells" & !is.na(nosub) &
                     Class == "Eutopic endometrium"),
        aes(color = after_stat(level))) +
    #scale_color_viridis_c(option = "B", direction = -1) +
    facet_grid(~ct) +
    theme_light()+
    theme(strip.background = element_blank(),
          axis.text.x = element_blank(),
          panel.grid = element_blank(),
          legend.position = "n")+labs(x="")

pF3<-pF1$data %>%
    filter(nosub != "Myeloid cells" & !is.na(nosub)) %>%
    ggplot(aes(x = umap_1, y = umap_2)) +
    geom_point(aes(col = nosub), size = .1,alpha=.1) +
    scale_color_manual(values = alt_cellcols) +
    new_scale_color() +
    stat_density_2d(
        data = pF1$data %>%
            filter(nosub != "Myeloid cells" & !is.na(nosub) &
                     Class == "Peritoneal endometriosis"),
        aes(color = after_stat(level)),) +
#    scale_color_viridis_c(option = "B", direction = -1) +
    facet_grid(~ct) +
    theme_light()+
    theme(strip.background = element_blank(),
          panel.grid = element_blank(),
          legend.position = "n")+labs(x="UMAP 1")

```
# CellChat
```{r}
library(CellChat)
library(ggrepel)

#names(alt_cellcols)<-sort(unique(aux_table$harmonized_major_plus_immune_cell_type))

cc_res<-readRDS("data/CellChat_PE_Eu.rds")
compareInteractions(cc_res[[1]], show.legend = F, group = c(1,2))

cc_res$`Eutopic endometrium`<-netAnalysis_computeCentrality(cc_res$`Eutopic endometrium`)
cc_res$`Peritoneal endometriosis`<-netAnalysis_computeCentrality(cc_res$`Peritoneal endometriosis`)

temp<-lapply(names(cc_res)[-1],function(x)
  rowSums(cc_res[[x]]@net$count)+colSums(cc_res[[x]]@net$count))
names(temp)<-names(cc_res)[-1]
temp<-lapply(names(temp), function(x) 
  temp[[x]]%>%as.data.frame()%>%mutate(Class=x)%>%
    rownames_to_column("ct"))%>%bind_rows()
colnames(temp)[2]<-"total_interactions"

pG<-temp%>%filter(ct!="Myeloid cells")%>%
    mutate(ct=factor(ct,levels=levels(pF0$data$nosub)))%>%
    ggplot(aes(y=ct,x=total_interactions,fill=Class))+
    geom_bar(stat="identity",position="fill")+
    geom_vline(xintercept = .5)+
    theme_classic()+theme(axis.line.y = element_blank(),
                          legend.position = "none")+
    scale_fill_manual(values=classcols)+
    labs(y="",x="Interaction proportion")
pG1<-temp%>%group_by(ct)%>%
  summarise(total_interactions=sum(total_interactions))%>%
  mutate(ct=str_replace(ct,"Memmory","Memory"))%>%
  mutate(ct=factor(ct,levels=levels(pG$data$ct)))%>%
  ggplot(aes(x=total_interactions,y=ct,fill=ct))+geom_col()+
  scale_fill_manual(values=alt_cellcols)+theme_classic()+
  theme(legend.position = "n",axis.text.y = element_blank(),
        axis.ticks.y=element_blank(),
        plot.margin=grid::unit(c(0,0,0,-3), "mm"))+
  labs(x="",y="")

cts<-unique(temp$ct)
#netVisual_diffInteraction() not working
pH<-netVisual_diffInteraction(cc_res[[1]],
                              comparison = c(1,2),
                              targets.use = "Mesothelial cells",
                              weight.scale = T,
                              remove.isolate = T)

pH1<-netVisual_diffInteraction(cc_res[[1]],
                              comparison = c(1,2),
                              sources.use = "Mesothelial cells",
                              weight.scale = T,
                              remove.isolate = T)
pH2<-netVisual_diffInteraction(cc_res[[1]],
                              comparison = c(1,2),
                              targets.use = "Plasmablast/Plasma cells",
                              weight.scale = T,
                              remove.isolate = T)

pH3<-netVisual_diffInteraction(cc_res[[1]],
                              comparison = c(1,2),
                              sources.use = "Plasmablast/Plasma cells",
                              weight.scale = T,
                              remove.isolate = T)

```
# CosMx neighbors
```{r}
temp<-edges%>%count(Class,type_to,type_from)
p0<-temp%>%filter(type_to==type_from&type_to!="")%>%
  ggplot(aes(x=Class,y=n,col=type_from,group=type_from))+
  geom_point()+geom_line()+
  scale_color_manual(values = cellcols)+scale_y_log10()+
  theme_light()+ggtitle("Homotypic interactions change")+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))
  labs(y="Interactions",col="",x="")

temp<-temp%>%filter(type_to!=""&type_from!="")%>%
  pivot_wider(names_from = type_to,values_from = n)%>%
  mutate(across(3:11,function(x) replace_na(x,0)))
temp1<-split(temp,f = temp$Class)%>%lapply(function(x) 
  x%>%mutate(across(3:11,function(y) 
    100*y/sum(y))))
cl<-temp1$`Eutopic endometrium`%>%select(-c(1,2))%>%t()%>%dist()%>%hclust(method = "complete")
temp1<-temp1%>%bind_rows()
temp1<-temp1[c(cl$order,9+cl$order),]
hm<-temp1%>%select(-c(1,2))%>%t()%>%
  Heatmap(name="%",column_split=temp1$Class,column_labels = temp1$type_from,
          col=colorRamp2(c(60,40,15,5,1,0),
                         c("#14081D","#651B79","#de7065ff","#FFC28B","#FCFDBF","white")),
          cluster_columns = cl,show_row_dend = F,row_names_side = "left",
          show_heatmap_legend = T,column_names_rot = 45)
hm<-grid.grabExpr(draw(hm))

plot_grid(hm,p0,align = "h",axis = "tb")


#partA<-plot_grid(pC+theme(axis.text = element_text(size=10),legend.position = "left",plot.margin=grid::unit(c(1,10,0,-3), "mm")),pC1+theme(axis.text = element_text(size=10),plot.margin=grid::unit(c(0,0,0,-15), "mm")),align="h",axis="tb",rel_widths = c(.8,.2),labels=c('B',''))
#partB<-plot_grid(pE+theme(axis.text = element_text(size=10)),pE1+theme(axis.text = element_text(size=10)),align="h",axis="tb",labels=c('C','D'))
#partA<-plot_grid(partA,partB,nrow = 2,rel_heights = c(.4,.6))
#partB<-plot_grid(pF1,pF2,nrow=2,align='v',axis="lr",rel_heights = c(.35,.65))
#partC<-plot_grid(pF,pG+theme(axis.text.y = element_blank(),axis.ticks.y =element_blank(),plot.margin=grid::unit(c(0,0,0,-10), "mm")),rel_widths = c(.7,.3),align = "h",axis = "tb")
#partC<-plot_grid(partC,NULL,nrow=2,rel_heights = c(.6,.4))
pdf("temp.pdf",width = 13,height = 11)
plot_grid(plot_grid(NULL,partA),plot_grid(partB,partC,rel_widths = c(.6,.4)),nrow=2)
dev.off()

save(hm0,p1,lgd0,pB,pB1,pC,pC1,pE,pH1,pI,
     p0,file="docs/Fig1.RData")

```

#supplementary Fig
```{r}
markers <- list(
#  "Myeloid" = c("CD68", "ITGAM", "CD14", "CD33", "CSF1R", "AIF1"),
  "Myeloid" = c("CD68", "CD33"),
  "M1" = c("IL1B","TNF","CXCL8","CXCL10"),
  "M2" = c("MRC1","CD163","FOLR2","CCL18"),
  "MDSC" = c("FCGR2A","S100A8","S100A9","FUT4","OLR1","FCN1","PTGS2", "VCAN", "LYZ", "FCGR3B", "CEACAM8", "CXCR2"),
  "Resident" = c("C1QA","C1QB","C1QC","SELENOP"),
  "APC" = c("HLA-DRA","CD74","FCER1A","CLEC10A"))

Idents(sub_myeloid)<-"myeloid_cl"
DotPlot(
    subset(sub_myeloid,idents = "undefined myeloid", invert = TRUE),
    features = markers,
    group.by = "myeloid_cl") +
    RotatedAxis()+
    theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))+
    scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")
```


