---
title: "Fig 2"
---
```{r}
library(tidyverse)
library(cowplot)
library(ComplexHeatmap)
library(circlize)
library(ggpubr)
library(ggrepel)
library(speckle)
library(limma)
library(ggridges)
library(dbscan)

domcol <- c( "gray13", "gold2", "lightskyblue2", "darkorange1", "plum4", "maroon")
names(domcol)<-6:1
classcols = c("Eutopic endometrium" = "#c2a5cf", 
              "Peritoneal endometriosis" = "#d9f0d3")
cellcols<-c("#8DB600","#fdae61","#a95f96","#0067A5","#604E97",
            "#f46d43","hotpink","#BE0032","cornflowerblue","black")
names(cellcols)<-c("B cells","Plasma cells","CD4 T cells","CD8 T cells",
                   "NK cells","Myeloid cells","unknown","Epithelial","Stroma")
dominantcols<-c(Epithelial="#BE0032",Stroma="cornflowerblue",Immune="forestgreen")
files<-list.files()
files<-files[str_detect(files,"bgclus")]
files<-files[-1]
metadata<-lapply(files,data.table::fread)%>%bind_rows()

i<-metadata%>%distinct(Run_Tissue_name,dom_nEndoh1_75)%>%
  count(dom_nEndoh1_75)%>%filter(n==1)%>%
  select(dom_nEndoh1_75)%>%unlist()
metadata<-metadata%>%filter(dom_nEndoh1_75!=i&!fov_type%in%c("unknown","low_signal"))
```

# Supplementary heatmap
```{r}
files<-list.files("data",full.names = T)
files<-files[str_detect(files,"bg")][-1]#no endometrioma
metadata<-lapply(files,vroom::vroom)%>%bind_rows()
gc()

mat<-vroom::vroom("endometrium.csv")
mat<-vroom::vroom("PE.csv")
gc()    

i<-metadata%>%select(Run_Tissue_name,protodomain,cell_ID)%>%
  split(f = metadata$protodomain)
metagenes<-lapply(i,function(x) mat%>%filter(cell_ID%in%x$cell_ID)%>%select(-1)%>%colMeans())
temp<-metagenes%>%bind_cols()
metagenes<-as.matrix(metagenes)
rownames(metagenes)<-colnames(mat)[-1]

annot<-metadata%>%distinct(protodomain,Class,Run_Tissue_name,dom_nEndoh1_75)
annot<-annot%>%mutate(index=case_when(dom_nEndoh1_75==6~1,
                                   dom_nEndoh1_75==3~2,
                                   dom_nEndoh1_75==4~3,
                                   dom_nEndoh1_75==2~4,
                                   dom_nEndoh1_75==1~6,
                                   TRUE~dom_nEndoh1_75))#as defined in Fig2
metagenes<-metagenes[,annot$protodomain]
nobatch<-sva::ComBat(dat = metagenes,batch = annot$Run_Tissue_name,par.prior = T)
#cor_dist<-cor(nobatch)
#cl<-hclust(as.dist(1-cor_dist),method="ward.D2")

Heatmap(asinh(nobatch[str_detect(rownames(zscores),
                                 "Chann|IgG",negate = T),]/5),
        show_column_names = F,show_row_dend = F,
        clustering_method_columns = "ward.D2",
        use_raster = F,name="expr",
        top_annotation = HeatmapAnnotation(Class=annot$Class,
                                           D=annot$index,
                                           Sample=annot$Run_Tissue_name,
        col=list(Class=classcols,D=domcol,Sample=kelly.colours)),
        column_split  = annot$index,col = colorRamp2(c(-2,0,2,4,6),                           c("white","#FCFDBF","#FFC28B","#de7065ff","#651B79")))

```

# Composition heatmap
```{r}
compo<-metadata%>%
  count(dom_nEndoh1_75,fov_type)%>%
  group_by(dom_nEndoh1_75)%>%
  mutate(total=sum(n),prop=100*n/total)
compo<-compo%>%
  mutate(dominant=ifelse(str_detect(fov_type,"B|CD|Myel|Plas|NK"),"Immune",
                fov_type))%>%
  group_by(dom_nEndoh1_75,dominant)%>%summarise(prop=sum(prop))%>%
  group_by(dom_nEndoh1_75)%>%slice_max(prop)%>%
  select(-prop)%>%right_join(compo)
compo<-compo%>%distinct(dom_nEndoh1_75,total)%>%
  arrange(total)%>%rownames_to_column("index")%>%
  select(-total)%>%right_join(compo)

pA<-compo%>%mutate(index=factor(index,levels = 6:1))%>%
  ggplot(aes(x=fov_type,y=as.factor(index),fill=prop))+
    geom_tile()+scale_fill_viridis_c(option = "F",direction = -1,trans="sqrt")+
    theme_minimal()+labs(x="Cell type",y="Domain",fill="%")+
    theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))
pA1<-compo%>%mutate(index=factor(index,levels = 6:1))%>%
  ggplot(aes(x=1,y=index,fill=as.factor(index)))+
    geom_bar(stat="identity",position = "fill")+
    scale_fill_manual(values = domcol)+theme_void()+
    theme(legend.position = "n")
pA2<-compo%>%mutate(index=factor(index,levels = 6:1))%>%
  ggplot(aes(x=1,y=index,fill=dominant))+
  geom_bar(stat="identity",position = "fill")+
  scale_fill_manual(values = dominantcols)+theme_void()+
    theme(legend.position = "bottom",legend.direction = "vertical")
pA3<-compo%>%mutate(index=factor(index,levels = 6:1))%>%
  distinct(index,total)%>%
  ggplot(aes(x=total,y=index))+geom_col()+
  theme_classic()+scale_x_sqrt()+
  theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(),
        plot.margin=grid::unit(c(0,3,0,-6), "mm"),
        axis.text.x = element_text(angle=45,vjust=1,hjust=1))+
  labs(y="")

compo<-metadata%>%count(dom_nEndoh1_75,Class,name = "class_n")%>%
  right_join(compo)
compo<-compo%>%distinct(index,dom_nEndoh1_75,Class,class_n)%>%
  group_by(Class)%>%summarise(class_n=sum(class_n),index="Total")%>%
  bind_rows(compo)
pA4<-compo%>%mutate(index=factor(index,levels = 6:1))%>%
    ggplot(aes(x=class_n,y=index,fill=Class))+
    geom_bar(stat = "identity",position = "fill")+
    theme_classic()+labs(x="Cells",y="")+
    theme(axis.ticks.y = element_blank(),axis.text.y = element_blank(),
          axis.line.y = element_blank(),plot.margin=grid::unit(c(0,3,0,-6), "mm"),
          legend.position = "bottom",legend.direction = "vertical")+
    scale_fill_manual(values = classcols)


```


# Domain signature 
```{r}
mat<-vroom::vroom("PE.csv")%>%filter(cell_ID%in%metadata$cell_ID)
mat<-vroom::vroom("endometrium.csv")%>%
  filter(cell_ID%in%metadata$cell_ID)%>%bind_rows(mat)

metadata<-metadata%>%mutate(gr=paste0(Run_Tissue_name,":",dom_nEndoh1_75))
temp<-metadata%>%split(f = metadata$gr)%>%
  sapply(function(x) mat%>%filter(cell_ID%in%x$cell_ID)%>%
           select(-cell_ID)%>%colMeans)
submeta<-metadata%>%distinct(Run_Tissue_name,dom_nEndoh1_75,Class,gr)
bulk<-CreateSeuratObject(counts = temp[,submeta$gr],meta.data = submeta)
bulk<-NormalizeData(bulk)
bulk<-FindVariableFeatures(bulk,nfeatures = 50)
bulk<-ScaleData(bulk)
bulk<-RunPCA(bulk)
bulk<-harmony::RunHarmony(bulk,group.by.vars="Run_Tissue_name")
bulk<-RunUMAP(bulk,dims = 1:10,reduction = "harmony",reduction.name = "harmonized_umap")
domDEG<-FindAllMarkers(object = bulk,group.by = "dom_nEndoh1_75",test.use = "LR",
                       logfc.threshold = 0,return.thresh = 1)

domDEG<-pA$data%>%distinct(index,dom_nEndoh1_75)%>%
  mutate(dom_nEndoh1_75=as.character(dom_nEndoh1_75))%>%
  inner_join(domDEG,by = c("dom_nEndoh1_75"="cluster"))
i<-domDEG%>%filter(str_detect(gene,"Chann|IgG",negate = T)&p_val_adj<0.05)%>%
  group_by(index)%>%slice_max(avg_log2FC,n=3)
pB<-domDEG%>%filter(gene%in%i$gene)%>%
  mutate(gene=factor(gene,levels = i$gene))%>%
  ggplot(aes(y=index,x=gene,col=avg_log2FC,size=p_val_adj))+
  geom_point()+scale_size(range=c(5,1),trans = "sqrt",
                          breaks = c(0,1e-4,1e-2,1))+
  theme_classic()+scale_color_gradient2(low="#2166ac",mid = "#f7f7f7", high = "#b2182b")+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))+
  labs(x="Protein",y="Domain",col="LFC",size="Padj")


```
# Example space plots: squidpy
# Cell composition contrast
```{r}
dombars<-lapply(names(classcols),function(x)
    metadata%>%filter(Class==x)%>%count(Class,dom_nEndoh1_75)%>%
        ggplot(aes(y=Class,x=n,fill=as.factor(dom_nEndoh1_75)))+
        geom_bar(stat="identity",position="fill")+
        theme_void(base_size = 14)+scale_fill_manual(values=domcol)+
      labs(x="%",y="",fill="domain")+theme(legend.position="none")+
      ggtitle(x))
names(dombars)<-names(classcols)
cellbars<-lapply(names(classcols),function(x)
    metadata%>%filter(Class==x)%>%count(Class,fov_type)%>%
        ggplot(aes(y=Class,x=n,fill=fov_type))+
        geom_bar(stat="identity",position="fill")+
        theme_void()+scale_fill_manual(values=cellcols)+
      labs(x="%",y="",fill="domain")+theme(legend.position="none"))
names(cellbars)<-names(classcols)

temp<-metadata%>%count(Class,dom_nEndoh1_75,fov_type)
temp<-pA$data%>%distinct(index,dom_nEndoh1_75)%>%inner_join(temp)
pD<-temp%>%
    mutate(Class=factor(Class,levels=c("Peritoneal endometriosis",
                                       "Eutopic endometrium")),
           index=factor(index,levels=1:6))%>%
    ggplot(aes(y=Class,x=n,fill =fov_type))+geom_bar(stat="identity",position="fill")+
    facet_wrap(~index,ncol=3)+scale_fill_manual(values=cellcols)+
    theme_classic()+theme(strip.background = element_blank(),
                          strip.text.y = element_text(angle=0),
                          legend.position = "left")+
    labs(x="Proportion",fill="Cell type")

partD<-plot_grid(dombars$`Eutopic endometrium`,cellbars$`Eutopic endometrium`,
          dombars$`Peritoneal endometriosis`,cellbars$`Peritoneal endometriosis`,nrow=2,ncol=2,align="vh",axis = "lr")

pD1<-temp%>%group_by(index,fov_type)%>%summarise(n=sum(n))%>%
  ggplot(aes(x=n,y=index,fill=fov_type))+
  geom_bar(stat="identity",position="fill")+
  scale_fill_manual(values=cellcols)+
  theme_void()+theme(legend.position = "n")
#test
temp<-split(metadata,f = metadata$dom_nEndoh1_75)
props<-lapply(temp,function(x) 
  getTransformedProps(x$fov_type,
                      x$Run_Tissue_name))
temp<-lapply(temp,function(x)
  x%>%distinct(Class,Run_Tissue_name)%>%
      mutate(Class=str_replace(Class,".+ e","E")))

designM<-lapply(temp,function(x) model.matrix(~0+Class,data=x))#groups around 
fit<-lapply(1:6,function(x) lmFit(props[[x]]$TransformedProps,designM[[x]]))
cont<-lapply(designM,function(x)
  makeContrasts(ClassEndometriosis-ClassEndometrium,levels = x))
fit<-lapply(1:6,function(x) contrasts.fit(fit[[x]],cont[[x]]))
fit <- lapply(fit,eBayes, robust=TRUE)

res<-lapply(fit,function(x) topTable(x,number = length(cellcols),coef = 1))
res<-lapply(1:6, function(x)
  res[[x]]%>%as.data.frame()%>%
    rownames_to_column("cell_type")%>%
    mutate(dom=x))%>%bind_rows()
#nothing is significant
```
# Neighbors
```{r}
files<-list.files("nets",full.names = T)
files<-files[str_detect(files,"delau")]

edges<-lapply(files, read_csv)
names(edges)<-str_remove_all(files,"nets/|delaunay.+")
edges<-lapply(names(edges), function(x) 
  edges[[x]]%>%mutate(Run_Tissue_name=x))%>%bind_rows()
edges<-edges%>%filter(distance<=0.1)
edges<-edges%>%mutate(from=paste0(Run_Tissue_name,from),to=paste0(Run_Tissue_name,to))
edges<-metadata%>%
    select(cell_ID,fov_type,dom_nEndoh1_75)%>%
    right_join(edges,by = c("cell_ID"="from"))
colnames(edges)[1:3]<-c("from","type_from","dom_from")
edges<-metadata%>%
    select(cell_ID,fov_type,dom_nEndoh1_75)%>%
    right_join(edges,by = c("cell_ID"="to"))
colnames(edges)[1:3]<-c("to","type_to","dom_to")
edges<-metadata%>%distinct(Run_Tissue_name,Class)%>%right_join(edges)
edges<-edges%>%mutate(homodom=dom_to==dom_from,
                      homotypic=type_from==type_to)

edges<-edges%>%filter(homodom==TRUE)
temp<-edges%>%count(dom_to,type_from,type_to,homotypic)%>%
  filter(!(type_from=="unknown"|type_to=="unknown"))
temp$edge_type<-apply(temp,1,function(x) paste0(sort(x[2:3]),collapse = " - "))
temp<-temp%>%mutate(name_from=str_remove(edge_type," -.+"),name_to=str_remove(edge_type,".+- "))
temp<-temp%>%group_by(dom_to,edge_type)%>%mutate(n=sum(n))%>%
  select(-c(type_to,type_from))%>%distinct()
temp<-temp%>%group_by(dom_to)%>%
  mutate(total=sum(n),prop=100*n/total)%>%ungroup()

temp<-pA$data%>%distinct(index,dom_nEndoh1_75)%>%
  right_join(temp,by=c("dom_nEndoh1_75"="dom_to"))
pF<-temp%>%group_by(edge_type)%>%slice_max(prop)%>%
  mutate(name_to=factor(name_to,levels = c("Stroma","Plasma cells",
                                           "NK cells","Myeloid cells",
                                           "Epithelial","CD8 T cells",
                                           "CD4 T cells","B cells")))%>%
  ggplot(aes(x=name_from,y = name_to,col=as.factor(index),size=prop))+
  geom_point()+scale_color_manual(values=domcol)+
  scale_size(range = c(1,8),trans="sqrt",breaks = c(1,25,50,75))+
  theme_classic()+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))+
  labs(x="from",y="to")

temp<-temp%>%group_by(index)%>%mutate(total=sum(n),prop=100*n/total)
pF1<-temp%>%ggplot(aes(x=prop,y=index,col=as.factor(index)))+
    geom_violin()+geom_boxplot(width=.1)+
    geom_text_repel(data=temp%>%filter(prop>10),
                    aes(label=edge_type))+
    labs(y="domain",x="interaction partners")+scale_x_sqrt()+
    scale_color_manual(values=domcol)+theme_classic()+
    theme(legend.position = "n")

#density
temp<-edges%>%group_by(dom_to,Run_Tissue_name,type_to,type_from)%>%
  summarise(avg_dist=mean(distance))
temp<-pA$data%>%distinct(index,dom_nEndoh1_75)%>%
  right_join(temp,by=c("dom_nEndoh1_75"="dom_to"))
i<-temp%>%filter(dom_nEndoh1_75==6)%>%ungroup()%>%
  select(avg_dist)%>%unlist()%>%median()
pE<-temp%>%ggplot(aes(x=avg_dist,y=as.factor(index),
                      fill=as.factor(index),col=as.factor(index)))+
  geom_density_ridges()+geom_vline(xintercept = i)+
  scale_fill_manual(values = domcol)+
  scale_colour_manual(values = domcol)+xlim(c(0,.05))+
  theme_classic()+labs(x="Avg. Dist.",y="Domain")+
  theme(legend.position = "n",axis.line.y = element_blank(),
        axis.ticks.y = element_blank())


partA<-plot_grid(pA1,pA2,pA+theme(legend.position = "top"),pA3,pA4,pB,ncol=6,rel_widths = c(.05,.05,.3,.15,.15,.3),align = "h",axis = "tb")
partB<-plot_grid(pD,plot_grid(pE,partD),plot_grid(pF,pF1),nrow = 3)
pdf("temp.pdf",width = 13,height = 9)
 plot_grid(partA,plot_grid(pD1,partB,rel_widths = c(.4,.6)),nrow = 2,rel_heights = c(.3,.7))
dev.off()
```
# Blob size
```{r}
metadata<-metadata%>%filter(dom_nEndoh1_75==6)

samples<-unique(metadata$Run_Tissue_name)
#per sample
#eye selected, how to automatize??????
#samples<-c("6318B1-PT20"=7,"BEME005-3042A1-PT11"=9,"BEME209-Endometrium"=25,#15,
#           "BEME228-9152C4-PT14"=21,"BEME518_Endometriosis_1023-A2"=17,"BEME523-Endometriosis"=12,
#           "BEME541_Endometriosis-795R3"=11,"BEME550-Endometrium"=1,"BEME596-Endometrium"=46)
dom6<-metadata%>%split(by="Run_Tissue_name")
eps<-c(.05,.03,.018,.018,.1,.045,.0135,.05,.021)#overfitted 
names(eps)<-samples
dbcl <- lapply(names(dom6),function(x)
    dbscan(dom6[[x]]%>%select(x_slide_mm,y_slide_mm), eps = eps[x]))
names(dbcl)<-names(dom6)
blobs<-lapply(names(dom6), function(x)
  dom6[[x]]%>%select(Run_Tissue_name,cell_ID,x_slide_mm,y_slide_mm,
                     Class,Area.um2,fov_type,dom_nEndoh1_75)%>%
    mutate(dbcl=dbcl[[x]]$cluster))%>%bind_rows()
#blobs%>%ggplot(aes(x=x_slide_mm,y=y_slide_mm,col=as.factor(dbcl)))+
#  geom_point(size=1)+
#  facet_wrap(~Run_Tissue_name,scales="free")+
#  guides(col = guide_legend(override.aes = list(size = 5)))
blobs<-blobs%>%mutate(Class=str_replace(Class,".+ e","E"))%>%
              mutate(Class=factor(Class,levels=c("Endometrium","Endometriosis")))
pG<-blobs%>%count(Class,Run_Tissue_name,dbcl,name="Size")%>%
    ggplot(aes(x=Size,y=Class,fill=Class))+
    geom_density_ridges()+theme_classic()+
    scale_fill_manual(values=classcols)+
    theme(axis.line.y = element_blank(),
          axis.ticks.y = element_blank(),
          legend.position = "n")
```

## blob composition
```{r}
temp<-blobs%>%filter(str_detect(fov_type,"B|CD|Mye|Plas|NK"))%>%
  count(Class,Run_Tissue_name,dbcl,fov_type,name="cells")%>%
  group_by(Class,Run_Tissue_name,dbcl)%>%
  mutate(total=sum(cells),prop=100*cells/total)%>%
  ungroup()

#pH1<-temp%>%count(Class,fov_type)%>%
#  left_join(temp%>%distinct(Class,Run_Tissue_name,dbcl)%>%
#              count(Class,name = "total"))%>%mutate(prop=100*n/total)%>%
#  ggplot(aes(x=Class,y=prop,fill=fov_type))+geom_col()+facet_grid(~fov_type)+
#    theme_classic()+theme(axis.text.x = element_blank(),
#                                strip.background = element_blank(),
#                                plot.margin=grid::unit(c(0,0,-4,0), "mm"))+
#    labs(x="",y="% of instances")+
#  scale_fill_manual(values=cellcols)+theme(legend.position = "none")
#
#pH2<-temp%>%ggplot(aes(x=Class,y=prop,col=fov_type,group=Class))+
#    geom_violin()+
#    geom_jitter(aes(size=total),width = .1,alpha=0.5)+
#  scale_color_manual(values=cellcols)+
#    stat_compare_means(method = "wilcox.test",label="p.signif",
#                       hide.ns = T,comparisons = list(c("Endometrium","Endometriosis")))+
#  facet_grid(~fov_type)+theme_classic()+
#  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1),
#        strip.background = element_blank(),strip.text.x = element_blank())+
#    labs(x="",y="% per instance",size="Size")+
#    scale_color_manual(values=cellcols)+guides(col="none")
#partB<-plot_grid(pB0,pB1,nrow=2,align = "v",axis = "lr",rel_heights = c(.3,.7))
#partA<-plot_grid(plot_grid(pA0,NULL,nrow=2,rel_heights = c(.75,.25)),partB,rel_widths = c(.25,.75))

temp<-temp%>%ungroup()%>%mutate(box=cut(total,breaks = 10))
formula <- y ~ x    
pG1<-temp%>%filter(total<2000)%>%
  ggplot(aes(x= total, y= prop, group=fov_type,color = fov_type)) +
                  geom_smooth(method = "loess", formula = formula, se = F,)+
                  scale_color_manual(values=cellcols)+
              labs(x="Size",y='%',colour="Cell type")+
              scale_y_continuous(limit=c(0,NA))+theme_classic()+
              facet_wrap(~Class,nrow=2,scales = "free_y")+
              theme(legend.position="none",strip.background = element_blank())

```


