---
title: "Fig.4"
---
## CellChat to next fig?
```{r}
library(Seurat)
library(msigdbr)
library(clusterProfiler)
library(CellChat)
library(ggrepel)
library(ggpubr)
library(limma)
library(introdataviz)


sc<-readRDS("data/fixed_annotated_aux.seurat.rds")
sc<-subset(sc,cells = which(sc$Class=="Peritoneal endometriosis"&
                           !sc$harmonized_major_plus_immune_cell_type%in%c("Erythrocytes","Exclude")))
sc@meta.data<-sc@meta.data%>%mutate(has_LA=ifelse(LA_per_Sample>0,"LA+","LA-"))
Idents(sc)<-sc$has_LA
aux_table<-sc@meta.data

cellcols<-c("#BE0032","#66c2a5","cornflowerblue","#f46d43","#8DB600",
            "#fdae61","#a95f96","#d53e48","#0067A5","#604E97")
names(cellcols)<-c("Epithelial cells","Endothelial cells","Mesenchymal cells","Myeloid cells","B cells",
                   "Plasma cells","CD4 T cells","NK cells","CD8 T cells","Immune")

```

# Effect on non-immune cells
```{r}


#enepi<-sc@meta.data%>%filter(!is.na(published_epithelial_subtype)&epithelial_subcluster_type=="EnEpi cells")%>%rownames()
#ens<-sc@meta.data%>%filter(!is.na(published_mesenchymal_subtype)&mesenchymal_subcluster_type=="EnS cells")%>%rownames()
#ens<-subset(sc,cells = ens)
#enepi<-subset(sc,cells = enepi)

#deg<-lapply(list(ens,enepi), function(x) 
#  FindMarkers(x,ident.1 = "TRUE",ident.2 = "FALSE",test.use="MAST"))
#names(deg)<-c("ens","enepi")
#deg<-lapply(names(deg),function(x) deg[[x]]%>%rownames_to_column("gene")%>%mutate(cell_type=x))%>%bind_rows()
#write_csv(deg,file = "docs/has_laDEG.csv")

deg<-data.table::fread("docs/has_laDEG-ct100-MAST.tsv")#all EnEpi/Ens not jut the ones with subtypes
deg<-deg%>%filter(str_detect(cell_type,"EnS|EnEp|theli|Mesen|Smoot"))
deg<-deg%>%mutate(STATUS=case_when(avg_log2FC<=-1&p_val_adj<0.05~"LA-",
                                   avg_log2FC>1&p_val_adj<0.05~"LA+",TRUE~"NOT.SIG"))

#temp<-deg%>%count(STATUS,cell_type)%>%filter(STATUS!="NOT.SIG")%>%
#         mutate(n=ifelse(STATUS=="LA-",-n,n))
#pB<-temp%>%ggplot(aes(y=cell_type,x=n,fill=STATUS))+geom_col()+
#    theme_classic()+labs(x="DEG",y="",fill="higher on")+
#    scale_fill_manual(values=c("gray","black"))+
#    theme(legend.position = "bottom")+
#    scale_x_continuous(breaks = pretty(temp$n),labels=abs(pretty(temp$n)))
temp<-deg%>%filter(STATUS!="NOT.SIG")%>%count(cell_type,STATUS)%>%
  pivot_wider(names_from = STATUS,values_from = n)%>%column_to_rownames("cell_type")
temp<-temp[,c("LA-","LA+")]
pB<-Heatmap(temp,rect_gp = gpar(col = "white", lwd = 2),
            cell_fun = function(j, i, x, y, w, h, col) { 
              grid.text(temp[i, j], x, y,gp = gpar(fontsize = 10))},
            cluster_rows = F,cluster_columns = F,col=colorRamp2(c(800,400,100,50,10,0),                                                  c("#14081D","#651B79","#de7065ff","#FFC28B","#FCFDBF","white")),
            show_heatmap_legend = F,column_names_rot  = 0,row_names_side = "left",
            column_title = "DEG")

deg%>%filter(str_detect(cell_type,"EnS|Endo"))%>%
    ggplot(aes(x=avg_log2FC,y=-log10(p_val_adj),col=STATUS,size=pct.1))+geom_point()+
    geom_text_repel(data=deg%>%filter(str_detect(cell_type,"EnS|Endo")&STATUS!="NOT.SIG"&pct.1>.5)%>%
                        group_by(STATUS,cell_type)%>%slice_max(abs(avg_log2FC),n=5),
                    aes(x=avg_log2FC,y=-log10(p_val_adj),col=STATUS,label=gene),show.legend = F)+
    theme_bw()+theme(legend.position = "bottom",strip.background = element_blank(),legend.box = "vertical")+
    scale_color_manual(values = c("darkgreen", "#b2182b","grey"))+
    facet_grid(rows=vars(cell_type),scales="free_y")+
    labs(x="LFC",y="log10(p-val)")

gseares<-read_csv("docs/has_laDEG")
gseares<-gseares%>%filter(str_detect(cell_type,"EnS|EnEp|theli|Mesen|Smoot"))
gseares<-gseares%>%mutate(STATUS=ifelse(NES>0,"LA+","LA-"))
temp1<-gseares%>%count(cell_type,STATUS)%>%
  pivot_wider(names_from = STATUS,values_from = n)%>%
  column_to_rownames("cell_type")
temp1<-temp1[rownames(temp),colnames(temp)]
pB1<-Heatmap(temp1,rect_gp = gpar(col = "white", lwd = 2),
        cell_fun = function(j, i, x, y, w, h, col) { 
            grid.text(temp1[i, j], x, y,gp = gpar(fontsize = 10))},
        cluster_rows = F,cluster_columns = F,col=colorRamp2(c(30,15,5,1,0),                                                           c("#651B79","#de7065ff","#FFC28B","#FCFDBF","white")),
        show_heatmap_legend = F,column_names_rot  = 0,row_names_side = "left",
        column_title = "Pathways")
pB<-grid.grabExpr(draw(pB+pB1))

pC<-gseares%>%add_count(Description)%>%filter(n>1)%>%
    ggplot(aes(x=cell_type,y=Description,size = p.adjust))+geom_point(aes(col=NES))+
    scale_color_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+
    scale_size(range=c(8,1))+#,breaks = c(5*10e-5,5*10e-4,1),transform = "sqrt")+
    theme_classic()+labs(x="",y="")+
    theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))
#i<-temp%>%filter(str_detect(Description,"humor|lipo"))%>%separate_rows(core_enrichment,sep = '/')%>%distinct(core_enrichment)%>%unlist()
#i<-lapply(pairs, function(x) x%>%filter((ligand%in%j|receptor%in%j)&(source%in%c("EnEpi cells","EnS cells")|target%in%c("EnS cells","EnEpi cells"))))%>%bind_rows()
```

# Progeny
```{r}

progeny<-data.table::fread("data/progeney_scores.tsv")
progeny<-aux_table%>%rownames_to_column("Cell")%>%
  select(Cell,harmonized_major_cell_type,has_LA)%>%inner_join(progeny)
#progeny<-progeny%>%filter(harmonized_major_cell_type%in%c("EnEpi cells","EnS cells"))

temp<-progeny%>%mutate(LA=ifelse(has_LA=="LA-","n","y"))%>%drop_na()
temp<-split(temp,f = progeny$harmonized_major_cell_type)
designM<-lapply(temp,function(x) model.matrix(~0+LA,data=x))
fit<-lapply(names(temp),function(x) 
  lmFit(temp[[x]]%>%select(Androgen:WNT)%>%t,designM[[x]]))
names(fit)<-names(temp)
cont<-lapply(designM,function(x) makeContrasts(LAy-LAn,levels = x))
fit<-lapply(names(fit),function(x) contrasts.fit(fit[[x]],cont[[x]]))
fit <- lapply(fit, eBayes,robust=TRUE)
res<-lapply(fit,function(x) topTable(x,number = 17,coef = 1))
names(res)<-names(temp)
res<-lapply(names(res),function(x)
  res[[x]]%>%rownames_to_column("pathway")%>%mutate(celltype=x))%>%bind_rows()
#res%>%ggplot(aes(x=celltype,y=pathway,col=logFC,size=adj.P.Val))+geom_point()+scale_size(range=c(8,1))+scale_color_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+theme_minimal()+theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))+ggtitle("Limma of progeny scores, PE only (LA+ - LA-)")

i<-res%>%filter(adj.P.Val<0.01&str_detect(celltype,"EnS|EnEp|theli|Mesen|Smoot"))%>%
  distinct(pathway,celltype)
temp<-progeny%>%
  select(Cell,harmonized_major_cell_type,has_LA,unique(i$pathway))%>%
  pivot_longer(unique(i$pathway),names_to = "pathway",values_to = "activity")
temp<-temp%>%right_join(i,by=c("harmonized_major_cell_type"="celltype","pathway"))
pD<-temp%>%mutate(pathway=factor(pathway,levels=c("WNT","Estrogen","TGFb","Hypoxia")))%>%
  ggplot(aes(x=harmonized_major_cell_type,fill=has_LA,y=activity))+
  geom_split_violin()+facet_grid(~pathway)+theme_minimal()+
  scale_fill_manual(values=c("gray","black"))+
  theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1),
        legend.position = "bottom")+labs(x="")
```



```{r}

cc_res<-readRDS("data/CellChat_PE_hasLA_exclude.rds")

cc_res$`FALSE`<-netAnalysis_computeCentrality(cc_res$`FALSE`)
cc_res$`TRUE`<-netAnalysis_computeCentrality(cc_res$`TRUE`)

pA<-netAnalysis_diff_signalingRole_scatter(cc_res[-1],
                                           x.measure = "outdeg_unweighted",
                                           y.measure = "indeg_unweighted")
temp<-pA$data


i<-aux_table%>%
  count(has_LA,harmonized_major_plus_immune_cell_type)%>%
  filter(n<100)%>%
  distinct(harmonized_major_plus_immune_cell_type)%>%
  unlist()
alt_cellcols<-CellChat::scPalette(26)
alt_cellcols<-grDevices::colorRampPalette(alt_cellcols)(30)
names(alt_cellcols)<-sort(unique(aux_table$harmonized_major_plus_immune_cell_type))
names(alt_cellcols)<-str_replace(names(alt_cellcols),"-"," ")%>%str_remove("Plasmablast/")
cellcols<-cellcols[sort(names(cellcols))]
alt_cellcols[names(alt_cellcols)%in%names(cellcols)]<-cellcols[names(cellcols)%in%names(alt_cellcols)]
names(alt_cellcols)<-sort(unique(aux_table$harmonized_major_plus_immune_cell_type))
alt_cellcols<-alt_cellcols[names(alt_cellcols)%in%unique(sc$harmonized_major_plus_immune_cell_type)]

temp<-temp%>%filter(!labels%in%i)
i<-temp%>%filter(str_detect(labels,"Gamma|Endo|Smoo|M2|B|EnS|EnEp"))%>%distinct(labels)%>%unlist()
pA<-temp%>%ggplot(aes(x=x,y=y,col=labels))+geom_point()+
    geom_text_repel(data=temp%>%filter(labels%in%i),
                    aes(x=x,y=y,label=labels),show.legend = F)+
    theme_minimal(base_size = 14)+
    geom_hline(yintercept = 0)+geom_vline(xintercept = 0)+
    labs(x="Outgoing interactions",y="Incoming interactions")+
    guides(col=guide_legend(ncol=1))+labs(col="cell type")+
    scale_color_manual(values=alt_cellcols)

pairs <- list("LA-"=subsetCommunication(cc_res$`FALSE`),
              "LA+"=subsetCommunication(cc_res$`TRUE`))
pairs<-lapply(names(pairs), function(x) pairs[[x]]%>%mutate(has_LA=x))%>%bind_rows()

i<-pairs%>%distinct(interaction_name,has_LA)%>%add_count(interaction_name)%>%
  filter(n==1&has_LA=="hasLA")%>%select(interaction_name)%>%unlist()
i<-pairs%>%filter(interaction_name%in%i)%>%mutate(cellinter=paste0(source," -> ",target))%>%
  distinct(cellinter,interaction_name_2,prob,pathway_name)
i%>%ggplot(aes(x=interaction_name_2,y=cellinter,col=prob))+geom_point()+facet_grid(~pathway_name,scales="free",space="free")+theme_minimal()+theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1),strip.text.x = element_text(angle = 90,vjust = .5,hjust = 0))+scale_color_viridis_c(option = "H",trans="log10",labels=c("Min","Max"),breaks=c(1.2e-8,2.24e-5))

temp<-pairs%>%count(source,target,has_LA)%>%
  pivot_wider(names_from = has_LA,values_from = n)%>%
  mutate(across(hasLA:noLA,function(x) replace_na(x,0)))
g<-graph_from_data_frame(temp[,1:2],directed = F)
E(g)$weight=temp$hasLA
g<-igraph::simplify(g,remove.loops = F,edge.attr.comb ="sum")
adjmat<-get.adjacency(g,attr = "weight")
adjmat[lower.tri(adjmat)]<-0
adjmat<-adjmat%>%as.matrix()%>%as.data.frame()%>%
  rownames_to_column("g1")%>%
  pivot_longer(-1,names_to = "g2",values_to = "LA+")%>%
  filter(`LA+`>0)
g<-graph_from_data_frame(temp[,1:2],directed = F)
E(g)$weight=temp$noLA
g<-igraph::simplify(g,remove.loops = F,edge.attr.comb ="sum")
temp1<-get.adjacency(g,attr = "weight")
temp1[lower.tri(temp1)]<-0
temp1<-temp1%>%as.matrix()%>%as.data.frame()%>%
     rownames_to_column("g1")%>%
     pivot_longer(-1,names_to = "g2",values_to = "LA-")%>%
     filter(`LA-`>0)
adjmat<-adjmat%>%merge(temp1,by = c("g1","g2"),all.x = T,all.y = T)
adjmat<-adjmat%>%mutate(across(`LA+`:`LA-`,function(x) replace_na(x,0)),
                        across(`LA+`:`LA-`,function(x) x+1e-5),
                        FC=`LA+`/`LA-`,LFC=log(FC))
temp1<-adjmat%>%select(g1,g2,LFC)%>%pivot_wider(names_from = g2,values_from = LFC)%>%mutate(across(-1,function(x) replace_na(x,0)))%>%column_to_rownames("g1")
```
















# Markers
```{r}
i<-c("SERPING1","FOXO1","STAT3","CRYAB","FGF7","IDO1","MKI67","WNT4","CTNNB1")
pG1<-DotPlot(subset(sc,cells = which(sc$harmonized_major_cell_type=="EnEpi cells")),
             features = i,group.by = "has_LA")
pG<-DotPlot(subset(sc,cells = which(sc$harmonized_major_cell_type=="EnS cells")),
            features = i,group.by = "has_LA")
temp<-pG1$data%>%mutate(celltype="EnEpi cells")%>%
  bind_rows(pG$data%>%mutate(celltype="EnS cells"))
pG<-temp%>%ggplot(aes(x=features.plot,y=id,col=avg.exp.scaled,size = pct.exp))+
  geom_point()+facet_grid(rows=vars(celltype))+
  theme_bw()+theme(axis.text.x = element_text(angle=45,vjust = 1,hjust = 1),
                   panel.grid = element_blank(),strip.background = element_blank())+
  labs(x="",y="")+
  scale_colour_gradient2(low = "darkgreen", mid = "#f7f7f7", high = "#b2182b")+
  labs(size="Percent\nExpressed",col="Average\nexpression")


partA<-plot_grid(pA0,pC,pE2,pG,nrow=4,align = 'v',axis = 'lr',rel_heights = c(.3,.3,.3,.2))
partB<-plot_grid(pB0,pB1,nrow=2,align = "v",axis = 'lr',rel_heights =c(.2,.8))
partC<-plot_grid(pD,pE,pF,ncol=3,rel_widths = c(.3,.4,.3),align = 'h',axis = "tb")
```
# Do proteins match with transcritps?
```{r}
samples<-metadata%>%filter(dom_nEndoh1_75==6&Class=="Peritoneal endometriosis")%>%
  distinct(Run_Tissue_name)%>%unlist()
metadata<-metadata%>%filter(Run_Tissue_name%in%samples)

temp<-blobs%>%filter(Run_Tissue_name%in%samples)%>%
  group_by(Run_Tissue_name,dbcl)%>%
  summarise(x_min=min(x_slide_mm),
            x_max=max(x_slide_mm),
            y_min=min(y_slide_mm),
            y_max=max(y_slide_mm))
temp<-lapply(seq(0.05,1,length=10),function(x)
  temp%>%mutate(x_min=x_min-x,x_max=x_max+x,
                y_min=y_min-x,y_max=y_max+x))%>%bind_rows()
temp<-temp%>%group_by(Run_Tissue_name,dbcl)%>%mutate(level=1:n())%>%ungroup()
temp<-split(temp,f = temp$Run_Tissue_name)

metadata<-split(metadata,f = metadata$Run_Tissue_name)
neighs<-lapply(names(metadata), function(x)
  apply(temp[[x]],1,function(y) 
    metadata[[x]]%>%filter(x_slide_mm>as.numeric(y[3])&
                           x_slide_mm<as.numeric(y[4])&
                           y_slide_mm>as.numeric(y[5])&
                           y_slide_mm<as.numeric(y[6])&
                           str_detect(merged_corrected,"Epit|Mesen"))%>%
          distinct(cell_ID,Run_Tissue_name,dom_nEndoh1_75,merged_corrected)%>%
      mutate(level=y[7]))%>%
    bind_rows)%>%bind_rows
neighs<-neighs%>%group_by(cell_ID)%>%slice_min(level)%>%distinct()%>%ungroup()
metadata<-metadata%>%bind_rows()
#!!!!!!!!!!!!!!!!!!!!!!!!!!
#you already have this saved as neigh_temp.csv

neighs<-neighs%>%mutate(level=ifelse(dom_nEndoh1_75==6,0,level),
                        cell_id=str_replace(cell_ID,".+c_","c_"))
temp<-split(neighs,f = neighs$Run_Tissue_name)
get_expre<-function(sample_name){
     fname<-paste0("docs/",sample_name,"asinh.csv")
     mat<-data.table::fread(fname)
     mat<-mat%>%as.data.frame()%>%column_to_rownames("probe")
     mat<-mat[,temp[[sample_name]]$cell_id]
     colnames(mat)<-paste0(sample_name,colnames(mat))
     return(mat)}
neigh_mat<-lapply(names(temp),function(x) get_expre(x))
names(neigh_mat)<-names(temp)

i<-c("Beta-catenin","IL-1b","Ki-67","p53","pan-RAS","Ms IgG1","Rb IgG")
neigh_mat<-lapply(neigh_mat,function(x) t(x[i,])%>%
                    as.data.frame()%>%
                    rownames_to_column("cell_ID"))%>%bind_rows()
temp<-bind_rows(temp)
neigh_mat<-neigh_mat%>%left_join(neighs)

temp<-neigh_mat%>%group_by(Run_Tissue_name,merged_corrected,level)%>%
  summarise(`Beta-catenin`=mean(`Beta-catenin`-`Rb IgG`),
            p53=mean(p53-`Rb IgG`),
            `Ki-67`=mean(`Ki-67`-`Ms IgG1`),
            `pan-RAS`=mean(`pan-RAS`-`Ms IgG1`),
            `IL-1b`=mean(`IL-1b`-`Ms IgG1`))
temp%>%pivot_longer(`Beta-catenin`:`pan-RAS`,names_to = "probe",values_to = "avg")%>%ggplot(aes(x=level,group = Run_Tissue_name,col=Run_Tissue_name,y=avg))+geom_point()+facet_grid(rows=vars(merged_corrected),cols=vars(probe))+labs(x="Domain 6 ith neighbor")+stat_cor()

```


# maybe
```{r}
mesen<-subset(sc,cells = which(!is.na(sc$published_mesenchymal_subtype)))
i<-mesen@meta.data%>%
  count(published_mesenchymal_subtype,has_LA)%>%
  filter(n<30)%>%
  distinct(published_mesenchymal_subtype)%>%
  unlist()%>%as.character()
mesen<-subset(mesen,cells = which(!mesen$published_mesenchymal_subtype%in%i))

temp<-mesen@meta.data%>%distinct(has_LA,SampleName)
props<-getTransformedProps(mesen@meta.data$published_mesenchymal_subtype,
                           mesen@meta.data$SampleName)
props<-props$TransformedProps[,temp$Run_Tissue_name]
designM<-model.matrix(~0+has_LA,data=temp)#groups around replicates=samplename
fit<-lmFit(props,designM)
cont<-makeContrasts(has_LATRUE-has_LAFALSE,levels = designM)
fit<-contrasts.fit(fit,cont)
fit <- eBayes(fit, robust=TRUE)
res<-topTable(fit,number = nrow(props),coef = 1)
res<-res%>%rownames_to_column("cell_type")

res%>%arrange(logFC)%>%mutate(cell_type=factor(cell_type,levels=cell_type))%>%
  ggplot(aes(x=logFC,y=cell_type,fill=logFC,size=adj.P.Val))+
  geom_point(shape=21)+scale_size(range=c(8,1),breaks = c(0.5,0.05))+
  scale_fill_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  theme_minimal(base_size = 14)+
  labs(x="LFC",y="",col="LFC",size="Adj. P-val")


```


## Markers
```{r}
temp<-metadata%>%filter(dom_nEndoh1_75=="6")
temp<-split(temp,by = "Run_Tissue_name")
get_expre<-function(sample_name){
  fname<-paste0("docs/",sample_name,"asinh.csv")
  mat<-data.table::fread(fname)
  mat<-mat%>%as.data.frame()%>%column_to_rownames("probe")
  mat<-mat[,temp[[sample_name]]$cell_id]
  colnames(mat)<-paste0(sample_name,colnames(mat))
  return(mat)}
dom_mat<-lapply(names(temp),function(x) get_expre(x))
dom_mat<-dom_mat%>%bind_cols()


#could change for deg lfc instead
temp<-dom_mat%>%group_by(Class,Run_Tissue_name,merged_corrected)%>%summarise(across(`4-1BB`:`pan-RAS`,mean))
temp1<-temp%>%ungroup()%>%select(`4-1BB`:`pan-RAS`)%>%scale()
temp1<-temp%>%select(Class:merged_corrected)%>%bind_cols(temp1)
temp1<-temp1%>%pivot_longer(`4-1BB`:`pan-RAS`,names_to = "probe",values_to = "scaled")%>%group_by(Class,merged_corrected,probe)%>%summarise(mean_scaled=mean(scaled))%>%pivot_wider(names_from = Class,values_from = mean_scaled)
temp1<-temp1%>%filter(str_detect(merged_corrected,"theli|Mesen|NK|Plas",negate = T))

markers<-c("CD56","CD138","CD68","CD45","CD4","CD3","FABP4","CD8",
           "Channel-PanCK","Fibronectin","SMA","CD31","CD34","EpCAM")
weird <- scales::trans_new("signed",
                           transform=function(x) ifelse(x>0,
                                                        atan(x),
                                                        sign(x)*sqrt(abs(x))),
                           inverse=function(x) round(atan(x),1))

weird1 <- scales::trans_new("asin_like",
                           transform=function(x) ifelse(x<=1,
                                                        asin(sqrt(x)),
                                                        asinh(sqrt(x))),
                           inverse=function(x) round(sin(x)**2,1))


pD<-temp1%>%filter(!probe%in%markers)%>%
    ggplot(aes(x=`Peritoneal endometriosis`,y=`Eutopic endometrium`,col=merged_corrected))+
    geom_point()+
    geom_text_repel(data = temp1%>%
                        filter(`Peritoneal endometriosis`<=-.5&`Eutopic endometrium`>.5&!probe%in%markers)%>%
                        group_by(merged_corrected)%>%
                        slice_min(`Peritoneal endometriosis`,n=10)%>%
                        slice_max(`Eutopic endometrium`,n=5),
                    aes(x=`Peritoneal endometriosis`,y=`Eutopic endometrium`,label=probe),
                    show.legend = F)+scale_color_manual(values = cellcols)+
    theme_minimal(base_size = 14)+theme(legend.position = "none")+
    facet_wrap(~merged_corrected)+
    scale_x_continuous(transform = weird,breaks = c(-.5,0,.5))+
    scale_y_continuous(transform = weird1,breaks = c(0,.5,1,1.5,2))

```


## Sc dotplots
```{r}
library(Seurat)
library(readxl)

sc<-readRDS("data/fixed_annotated_aux.seurat.rds")
sc<-subset(sc,cells = which(sc$Class%in%c("Eutopic endometrium","Peritoneal endometriosis")&
                            !is.na(sc$Final_Immune_Cluster_ID)))
sc@meta.data<-sc@meta.data%>%
  mutate(harmonized_major_cell_type=ifelse(harmonized_major_plus_immune_cell_type=="Early Exhausted CD8 T-cells (2)",
                                           "T cells",harmonized_major_cell_type),
         has_LA=case_when(LA_per_Sample>0~"LA+",
                          LA_per_Sample==0~"LA-",
                          TRUE~Class))

tcells<-subset(sc,cells = which(sc$harmonized_major_cell_type=="T cells"))
signatures<-read_excel("../../Downloads/41591_2023_2371_MOESM3_ESM.xlsx",sheet = 5,skip = 1)
signatures<-signatures%>%
  mutate(dummy="lala")%>%
  pivot_longer(-dummy,names_to = "signature",values_to = "gene")%>%
  drop_na()
signatures<-split(signatures,f = signatures$signature)%>%
  lapply(function(x) x$gene)
signatures<-lapply(signatures, function(x) x[x%in%rownames(tcells)])

tcells <- AddModuleScore(stcellsc,features = signatures)
colnames(tcells@meta.data)[173:191]<-str_replace_all(names(signatures)," ","_")
```
### tcells
```{r}
tcells<-subset(sc,cells = which(sc$harmonized_major_cell_type=="T cells"))
i<-tcells@meta.data%>%count(has_LA,Final_Immune_Cluster_ID)%>%
  filter(n>=100)%>%distinct(Final_Immune_Cluster_ID)%>%unlist()
tcells<-subset(tcells,cells = which(tcells$Final_Immune_Cluster_ID%in%i))

signatures<-read_excel("../../Downloads/41591_2023_2371_MOESM3_ESM.xlsx",sheet = 5,skip = 1)
signatures<-signatures%>%
  mutate(dummy="lala")%>%
  pivot_longer(-dummy,names_to = "signature",values_to = "gene")%>%
  drop_na()
signatures<-split(signatures,f = signatures$signature)%>%
  lapply(function(x) x$gene)
signatures<-lapply(signatures, function(x) x[x%in%rownames(tcells)])
signatures$`CGAS-STINGactivation`<-c("TMEM173","CGAS","IFI16","ATM")
signatures$`CGAS-STINGresponse`<-c("CCL5","CXCL9","CXCL10")
tcells <- AddModuleScore(tcells,features = signatures)
colnames(tcells@meta.data)[173:193]<-names(signatures)

temp<-tcells@meta.data%>%select(has_LA,SampleName,Final_Immune_Cluster_ID,
                                `Activation:Effector function`:`CGAS-STINGresponse`)
temp<-split(temp,f = temp$Final_Immune_Cluster_ID)
designM<-lapply(temp,function(x) model.matrix(~0+has_LA+SampleName,data=x)) 

fit<-lapply(names(temp),function(x) 
  lmFit(temp[[x]]%>%select(`Activation:Effector function`:`CGAS-STINGresponse`)%>%t(),
        designM[[x]]))
names(fit)<-names(temp)
cont<-lapply(designM,function(x) makeContrasts(has_LATRUE-has_LAFALSE,levels = x))
fit<-lapply(names(fit),function(x) contrasts.fit(fit[[x]],cont[[x]]))
names(fit)<-names(temp)
fit <- lapply(fit,eBayes, robust=TRUE)
res<-lapply(fit,function(x) topTable(x,number = length(signatures),coef = 1))
res<-lapply(names(res), function(x)
  res[[x]]%>%rownames_to_column("signature")%>%mutate(cell_type=x))%>%bind_rows()
i<-res%>%filter(adj.P.Val<0.05&AveExpr>.1)

temp<-lapply(unique(tcells$has_LA),function(x) DotPlot(subset(tcells,cells=which(tcells$has_LA==x)),group.by = "Final_Immune_Cluster_ID",features = unique(i$signature)))
names(temp)<-unique(tcells$has_LA)
temp<-lapply(names(temp), function(x) temp[[x]]$data%>%mutate(has_LA=x))%>%bind_rows()
pF<-temp%>%ggplot(aes(x=has_LA,y=id,col=avg.exp,size=pct.exp))+geom_point()+facet_grid(~features.plot)+theme_minimal(base_size = 14)+theme(strip.background = element_blank(),strip.text.x = element_text(angle=90,vjust = .5,hjust =0))+scale_color_viridis_c(option = "A")+labs(x="",y="Cell type",col="Average\nexpression",size="Percent\nexpression")

```
### b cells
```{r}
markers<-list("B cells"=c("CD79A","MS4A1","CD19"),
              Follicular=c("IGHD","CR2","CD22","FCER2","CD24","BCL2"),
              Activated=c("CD27","IL2RA","TNFRSF8","CD69","CD70","CD80","CD86","FLT3"),
              "Germinal center"=c("MME","TNFRSF17","BCL6","AICDA"),
              #"Tissue-like memory"=c("IGHG1","IGHG3","FCRL5"),
              "Antibody-secreting"=c("CD38","MKI67","SDC1","PRDM1"))
markers<-markers%>%reshape2::melt()%>%mutate(marker=value)%>%select(-value)%>%deframe()

bcells<-subset(sc,cells = which(sc$harmonized_major_cell_type=="B cells"),features=markers)
bcells <- RunPCA(bcells)
bcells <- RunUMAP(bcells, dims = 1:5)
bcells <- FindNeighbors(bcells, dims = 1:5)
bcells <- FindClusters(bcells, resolution = 0.03)
DimPlot(bcells,group.by = "SCT_snn_res.0.03")

pG0<-DotPlot(bcells,group.by = "SCT_snn_res.0.03",features = markers)+RotatedAxis()+scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+theme(strip.text.x = element_text(angle=90,vjust = .5,hjust =0))+labs(x="",y="B subcluster",col="Scaled\nexpression",size="Percent\nexpressed")

temp<-bcells@meta.data%>%count(bclust,has_LA)
pG1<-temp%>%mutate(bclust=factor(bclust,levels=rev(unique(pG0$data$id))))%>%ggplot(aes(x=n,y=ifelse(has_LA=="TRUE","LA+","LA-")))+geom_col()+facet_grid(rows=vars(bclust),scales="free_y")+scale_x_sqrt()+labs(x="Cells",y="")+theme_classic(base_size = 14)+theme(strip.background = element_blank(),plot.margin=grid::unit(c(2,2,2,-5), "mm"),panel.spacing.y = unit(.05, "lines"),strip.text = element_blank())
plot_grid(pG0+theme(legend.position = "none"),pG1,get_legend(pG0),ncol=3,align = 'h',axis = 'tb',rel_widths = c(.45,.45,.1))
```

### myeloid cells
```{r}
myel<-subset(sc,cells = which(sc$harmonized_major_cell_type=="Myeloid cells"))
m_df <- msigdbr(species = "Homo sapiens")%>%
    filter(str_detect(gs_name,"REACTOME"))%>%
    distinct(gs_name,gene_symbol)

i<-c("REACTOME_SIGNALING_BY_EGFR","REACTOME_EGFR_DOWNREGULATION",
     "REACTOME_CYTOKINE_SIGNALING_IN_IMMUNE_SYSTEM",
     "REACTOME_DISEASES_OF_SIGNAL_TRANSDUCTION_BY_GROWTH_FACTOR_RECEPTORS_AND_SECOND_MESSENGERS",
     "REACTOME_GROWTH_HORMONE_RECEPTOR_SIGNALING",
     "REACTOME_STING_MEDIATED_INDUCTION_OF_HOST_IMMUNE_RESPONSES",
     "REACTOME_INTERLEUKIN_18_SIGNALING",
     "REACTOME_INTERLEUKIN_1_FAMILY_SIGNALING",
     "REACTOME_REGULATION_OF_IFNA_IFNB_SIGNALING",
     "REACTOME_REGULATION_OF_IFNG_SIGNALING")
signatures<-m_df%>%filter(gs_name%in%i)
signatures<-split(signatures,f = signatures$gs_name)%>%
  lapply(function(x) x$gene_symbol[x$gene_symbol%in%rownames(sc)])
signatures$`CGAS-STINGactivation`<-c("TMEM173","CGAS","IFI16","ATM")
signatures$`CGAS-STINGresponse`<-c("CCL5","CXCL9","CXCL10")

sc <- AddModuleScore(sc,features = signatures)
colnames(sc@meta.data)[173:180]<-names(signatures)

temp<-sc@meta.data%>%select(has_LA,SampleName,Final_Immune_Cluster_ID,
                            names(signatures))
temp<-split(temp,f = temp$Final_Immune_Cluster_ID)
designM<-lapply(temp,function(x) model.matrix(~0+has_LA+SampleName,data=x)) 

fit<-lapply(names(temp),function(x) 
  lmFit(temp[[x]]%>%select(4:11)%>%t(),
        designM[[x]]))
names(fit)<-names(temp)
cont<-lapply(designM,function(x) makeContrasts(has_LATRUE-has_LAFALSE,levels = x))
fit<-lapply(names(fit),function(x) contrasts.fit(fit[[x]],cont[[x]]))
names(fit)<-names(temp)
fit <- lapply(fit,eBayes, robust=TRUE)
res<-lapply(fit,function(x) topTable(x,number = length(signatures),coef = 1))
res<-lapply(names(res), function(x)
  res[[x]]%>%rownames_to_column("signature")%>%mutate(cell_type=x))%>%bind_rows()

temp<-lapply(unique(sc$has_LA),function(x) DotPlot(subset(sc,cells=which(sc$has_LA==x)),group.by = "Final_Immune_Cluster_ID",features = names(signatures)))
names(temp)<-unique(sc$has_LA)
temp<-lapply(names(temp), function(x) temp[[x]]$data%>%mutate(has_LA=x))%>%bind_rows()

temp%>%filter(harmonized_major_cell_type%in%c("T cells","Myeloid cells")&!Final_Immune_Cluster_ID%in%c("Exhausted CD8 T-cells","Early Exhausted CD8 T-cells (2)"))%>%mutate(features.plot=str_remove(features.plot,"REACTOME_"))%>%ggplot(aes(y=has_LA,x=Final_Immune_Cluster_ID,col=avg.exp,size=pct.exp))+geom_point()+facet_grid(rows=vars(features.plot),cols=vars(harmonized_major_cell_type),scales="free_x")+theme_minimal(base_size = 14)+theme(strip.background = element_blank(),strip.text.y.right = element_text(angle=0,vjust = .5,hjust =0),axis.text.x = element_text(angle=45,vjust = 1,hjust = 1))+scale_color_viridis_c(option = "A")+labs(x="",y="Cell type",col="Average\nexpression",size="Percent\nexpression")


```



