---
title: "LA contrast exploration"
---


```{r}
library(htmltools)#otherwise seurat dies, to fix
library(Seurat)
library(tidyverse)
library(cowplot)
library(ggplot2)
library(speckle)
library(limma)
library(ggpubr)
library(clusterProfiler)
library(msigdbr)

kelly.colours <- c("gray95", "gray13", "gold2", "plum4", "darkorange1", "lightskyblue2", "firebrick", "burlywood3", "gray51", "springgreen4", "lightpink2", "deepskyblue4", "lightsalmon2", "mediumpurple4", "orange", "maroon", "yellow3", "brown4", "yellow4", "sienna4", "chocolate", "gray19")
cluster.cols = c("#8DB600", "#d53e48", "#f46d43", "#fdae61", "#ffffbf", "#e6f598", "#abdda4", "#66c2a5", "#3288bd",'#9e0142', '#604E97', '#E25822','#008856', '#BE0032', '#0067A5')

sc<-readRDS("data/fixed_annotated_aux.seurat.rds")
aux_table<-sc@meta.data
```

# Cell composition per LA status
### scatterplot
```{r}
aux_la<-read_tsv("data/LA_aux.tsv")#from LA_bioinfo:Marcela
colnames(aux_la)[1:2]<-c("LA_patient","LA_sample")
aux_table<-aux_table%>%
  filter(Class=="Peritoneal endometriosis")%>%
  left_join(aux_la,by = "SampleName")

temp<-composition%>%inner_join(aux_la,by = "SampleName")%>%
  mutate(has_LA=LA_sample>0)
temp%>%filter(Class=="Peritoneal endometriosis")%>%
  ggplot(aes(x=prop,y=LA_sample))+geom_point()+
  facet_wrap(~harmonized_major_plus_immune_cell_type,scales = "free")
```
### speckle
```{r}
temp<-aux_table%>%distinct(has_LA,SampleName)
props<-getTransformedProps(aux_table$harmonized_major_plus_immune_cell_type,
                           aux_table$SampleName)
designM<-model.matrix(~0+has_LA,data=temp)#groups around 

props<-props$TransformedProps[,temp$SampleName]
fit<-lmFit(props,designM)
cont<-makeContrasts(has_LATRUE-has_LAFALSE,levels = designM)
fit<-contrasts.fit(fit,cont)
fit <- eBayes(fit, robust=TRUE)

res<-topTable(fit,number = nrow(props),coef = 1)
p1<-res%>%arrange(logFC)%>%rownames_to_column("cell_type")%>%filter(cell_type!="Exclude")%>%mutate(cell_type=factor(cell_type,levels=cell_type))%>%ggplot(aes(x=logFC,y=cell_type,fill=logFC,size=adj.P.Val))+geom_point(shape=21)+scale_size(range=c(8,1),breaks = c(0.5,0.05))+scale_fill_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+theme_classic(base_size = 14)+ggtitle("LA - no LA")

temp<-aux_table%>%count(has_LA,harmonized_major_plus_immune_cell_type,name = "cell_n")%>%
    group_by(has_LA)%>%
    mutate(total=sum(cell_n),prop=100*cell_n/total)
temp<-temp%>%group_by(harmonized_major_plus_immune_cell_type)%>%summarise(cell_n=sum(cell_n),has_LA="Total")%>%ungroup()%>%mutate(total=sum(cell_n),prop=100*cell_n/total)%>%bind_rows(temp%>%mutate(has_LA=as.character(has_LA)))

p0<-temp%>%ggplot(aes(y=cell_n,x=has_LA,fill=harmonized_major_plus_immune_cell_type))+geom_bar(stat="identity",position = "fill")+scale_fill_manual(values=unique(c(kelly.colours,cluster.cols)))

```

# barplot LA vs no
```{r}
temp<-aux_table%>%
  filter(str_detect(Final_Immune_Cluster_ID,"T-cells"))%>%
  count(has_LA,Final_Immune_Cluster_ID)
temp<-temp%>%
  group_by(Final_Immune_Cluster_ID)%>%
  mutate(total=sum(n),prop=round(100*n/total,2))
i<-temp%>%
  filter(has_LA==TRUE)%>%arrange(prop)%>%
  select(Final_Immune_Cluster_ID)%>%
  unlist()
temp<-temp%>%group_by(has_LA)%>%summarise(n=sum(n),
                                          total=25240+20806,
                                          prop=round(100*n/total,2),
                                          Final_Immune_Cluster_ID="Total")%>%bind_rows(temp)
temp<-temp%>%
  mutate(Final_Immune_Cluster_ID=factor(Final_Immune_Cluster_ID,levels=c(i,"Total")))

p0<-temp%>%ggplot(aes(y = Final_Immune_Cluster_ID, x = prop, fill = has_LA, label = prop)) + 
    geom_bar(position="stack",stat = "identity", width=0.8) +
    geom_text(position = position_stack(vjust = 0.5), size = 4) +
    theme_classic(base_size = 14)+labs(x='%',y="")+theme(axis.line.y = element_blank(),axis.ticks.y = element_blank())
p1<-temp%>%distinct(Final_Immune_Cluster_ID,total)%>%
  mutate(total=ifelse(Final_Immune_Cluster_ID=="Total",0,total))%>%
  ggplot(aes(x=total,y=Final_Immune_Cluster_ID))+geom_col()+theme_classic(base_size = 14)+
  theme(axis.text.y =element_blank(),axis.line.y = element_blank(),axis.ticks.y = element_blank() )+labs(y="")
p0<-plot_grid(p0+theme(legend.position = "none"),p1,get_legend(p0),align = 'h',axis = "tblr",rel_widths = c(.6,.3,.1),ncol = 3)

```

### cor
```{r}
temp<-temp%>%select(SampleName,harmonized_major_plus_immune_cell_type,LA_sample,prop,cell_n)%>%group_by(harmonized_major_plus_immune_cell_type)%>%summarise(cor=cor.test(LA_sample,prop)$estimate,pval=cor.test(LA_sample,prop)$p.value,cell_n=sum(cell_n))

temp%>%arrange(cell_n)%>%mutate(harmonized_major_plus_immune_cell_type=factor(harmonized_major_plus_immune_cell_type,levels=harmonized_major_plus_immune_cell_type))%>%ggplot(aes(x=cell_n,y=harmonized_major_plus_immune_cell_type,fill=cor,size=pval))+geom_point(shape=21)+scale_size(range=c(8,1),breaks = c(0.5,0.05))+scale_fill_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+scale_x_continuous(trans="log10")
```

# Progeny
```{r}
progeny<-data.table::fread("data/progeney_scores.tsv")
la_aux<-read_tsv("data/LA_aux.tsv")
colnames(la_aux)[2]<-"LA_perSample"

la_aux<-la_aux%>%select(LA_perSample,SampleName)%>%
  right_join(aux_table%>%select(barcode,harmonized_major_plus_immune_cell_type,Class,SampleName),
             by="SampleName")
la_aux<-la_aux%>%left_join(progeny,by=c("barcode"="Cell"))
la_auxPE<-la_aux%>%filter(Class=="Peritoneal endometriosis")
la_auxPE<-la_auxPE%>%mutate(has_LA=LA_perSample>0)%>%pivot_longer(Androgen:WNT,names_to = "pathway",values_to = "activity")
la_auxPE%>%ggplot(aes(x=has_LA,y=activity))+geom_violin()+geom_jitter(position=position_jitter(width=0.1, height=0))+facet_wrap(~pathway)+stat_compare_means(label = 'p')

enepi<-aux_table%>%filter(!is.na(published_epithelial_subtype)&epithelial_subcluster_type=="EnEpi cells")%>%select(barcode)%>%unlist()
ens<-aux_table%>%filter(!is.na(published_mesenchymal_subtype)&mesenchymal_subcluster_type=="EnS cells")%>%select(barcode)%>%unlist()
mesen<-la_auxPE%>%filter(harmonized_major_cell_type=="Mesenchymal cells"&!barcode%in%c(enepi,ens))%>%select(barcode)%>%unlist()

la_auxPE%>%filter(barcode%in%enepi)%>%ggplot(aes(x=has_LA,y=activity))+geom_violin()+geom_jitter(position=position_jitter(width=0.05, height=0))+facet_wrap(~pathway)+stat_compare_means(label = 'p')+ggtitle("EnEpi cells")
```

# DEA
```{r}
library(igraph)

sc<-subset(sc,cells = which(sc$Class=="Peritoneal endometriosis"))
la_aux<-read_tsv("data/LA_aux.tsv")
colnames(la_aux)[2]<-"LA_per_Sample"
la_aux<-la_aux%>%select(LA_perSample,SampleName)%>%
     right_join(sc@meta.data%>%rownames_to_column("barcode")%>%select(barcode,SampleName))
la_aux<-la_aux[order(match(la_aux$barcode,colnames(sc))),]
sc<-AddMetaData(sc,metadata = la_aux%>%select(-SampleName),col.name = "LA_per_Sample")
sc$has_LA<-sc$LA_per_Sample>0
Idents(sc)<-sc$has_LA

ens<-subset(sc,cells = ens)
enepi<-subset(sc,cells = enepi)
mesen<-subset(sc,cells = mesen)
deg<-lapply(list(ens,enepi,mesen), function(x) 
  FindMarkers(x,ident.1 = "TRUE",ident.2 = "FALSE",test.use="MAST"))

deg<-lapply(names(deg),function(x) deg[[x]]%>%rownames_to_column("gene")%>%mutate(cell_type=x))%>%bind_rows()
write_tsv(deg,"has_laDEG.csv")

deg<-deg%>%mutate(STATUS=case_when(avg_log2FC<=-2.5&p_val_adj<0.01~"Down",avg_log2FC>2.5&p_val_adj<0.01~"Up",TRUE~"NOT.SIG"))

p2<-deg%>%filter(cell_type=="mesen")%>%ggplot(aes(x=avg_log2FC,y=-log10(p_val_adj),col=STATUS))+geom_point()+ggtitle("Mesenchymal cells, p_val: 0.01, LFC: 2.5, Down: 42, Up: 7")+geom_text_repel(data=deg%>%filter(cell_type=="mesen"&STATUS!="NOT.SIG")%>%slice_max(abs(avg_log2FC),n=10),aes(x=avg_log2FC,y=-log10(p_val_adj),col=STATUS,label=gene),show.legend = F)+theme_classic(base_size = 14)+theme(legend.position = "bottom")


m_df <- msigdbr(species = "Homo sapiens")%>%
    filter(str_detect(gs_name,"REACTOME"))%>%
    distinct(gs_name,gene_symbol)
temp<-deg%>%filter(p_val_adj<0.01 & abs(avg_log2FC)>1)%>%
  mutate(STATUS=ifelse(avg_log2FC<0,"Down","Up"))%>%
  unite("cluster",cell_type:STATUS,remove = F)
oraRes<-temp%>%split(temp$cluster)%>%lapply(function(x) enricher(x$gene,TERM2GENE = m_df))
oraRes<-lapply(names(oraRes),function(x) 
  oraRes[[x]]%>%as.data.frame()%>%mutate(cluster=x))%>%bind_rows()
oraRes%>%separate(cluster,into = c("cell_type","STATUS"),remove = F)%>%ggplot(aes(x=cell_type,y=str_remove(ID,"REACTOME_"),col=p.adjust,fill=p.adjust,size=Count,shape=STATUS))+geom_point()+scale_shape_manual(values=24:25)+labs(x="",y="")+theme_classic(base_size = 14)

temp<-split(oraRes,f = oraRes$cluster)%>%lapply(function(x) x%>%separate_rows(geneID,sep = "/")%>%distinct(ID,geneID))
edges<-lapply(temp,function(x)
  table(x)%>%crossprod()%>%as.data.frame()%>%rownames_to_column("g1")%>%pivot_longer(-1,names_to = "g2",values_to = "functions"))
g<-lapply(edges,function(x) graph_from_data_frame(x[,1:2],directed = F))
E(g$EnEpi_Down)$weight<-edges$EnEpi_Down$functions
V(g$EnEpi_Down)$size<-temp$EnEpi_Down%>%count(geneID)%>%select(n)%>%unlist()
g<-lapply(g,function(x) simplify(x,remove.loops = T,remove.multiple = T,edge.attr.comb = "random"))
plot.igraph(g,vertex.color="gray",vertex.label.color="black",vertex.frame.color=NA,vertex.size=5*V(g)$size,width=E(g)$weight,layout=layout_with_dh,edge.color="#909090")

```
# Dotplot groups DEG
```{r}
tcells<-subset(sc,cells = which(str_detect(sc$Final_Immune_Cluster_ID,"T-cells")))
tlabels<-unique(tcells$Final_Immune_Cluster_ID)
tcells<-lapply(tlabels, function(x) subset(tcells,cells=which(tcells$Final_Immune_Cluster_ID==x)))
tcellDEG<-lapply(tcells, function(x) FindMarkers(x,ident.1 = "TRUE",ident.2 = "FALSE",test.use="MAST"))

file<-list.files("docs",full.names = T)
file<-file[str_detect(file,"chemo|inter|tnf|comple|")]
groups<-lapply(file,function(x) read_csv(x,skip=1))
names(groups)<-str_remove_all(file,"docs/|.csv")
groups<-lapply(names(groups), function(x) groups[[x]]%>%mutate(group=x))%>%bind_rows()

i<-tcellsDEG%>%inner_join(groups,by=c("gene"="Approved symbol"))%>%filter(p_val_adj<0.05)
i<-i%>%distinct(group,gene)%>%deframe()
i<-i[order(names(i))]

mesen<-subset(sc,cells = which(!is.na(sc$published_mesenchymal_subtype)&sc$harmonized_major_cell_type=="Mesenchymal cells"))
labels<-unique(mesen$published_mesenchymal_subtype)
subsets<-lapply(labels, function(x) subset(mesen,cells=which(mesen$published_mesenchymal_subtype==x)))
names(subsets)<-labels
mesenDEG<-lapply(subsets, function(x) FindMarkers(x,ident.1 = "TRUE",ident.2 = "FALSE",test.use="MAST"))



```

#mesen markers
```{r}
markers<-list(stromal=c("PTPRC","PECAM1"),
              FRC=c("PDPN","ACTA2","DES","COL1A1","IL7",
                    "CCL19","CCL21","PDGFRA","PDGFRB"),
              MRC=c("MADCAM1","TNFSF11","CXCL13"),
              FDC=c("CR2","CR1","TNFSF13B"),
              CRC=c("CXCL12","COL4A1"),
              VSC=c("THBD","VCAM1"),
              "FRC-like fibroblast"="BST1")
markers<-markers%>%reshape2::melt()%>%
  mutate(marker=value)%>%select(-value)%>%deframe()
```

```{r}
#aux_table already include has_LA
mesen<-aux_table%>%filter(Class=="Peritoneal endometriosis"&
                            harmonized_major_cell_type=="Mesenchymal cells"&
                            published_mesenchymal_subtype!=""&
                            !is.na(published_mesenchymal_subtype))
props<-getTransformedProps(mesen$published_mesenchymal_subtype,
                           mesen$SampleName)
designM<-model.matrix(~0+has_LA,data=mesen%>%distinct(has_LA,SampleName))#groups around 

props<-props$TransformedProps[,mesen%>%distinct(has_LA,SampleName)%>%select(SampleName)%>%unlist()]
fit<-lmFit(props,designM)
cont<-makeContrasts(has_LATRUE-has_LAFALSE,levels = designM)
fit<-contrasts.fit(fit,cont)
fit <- eBayes(fit, robust=TRUE)

res<-topTable(fit,number = nrow(props),coef = 1)
p1<-res%>%arrange(logFC)%>%rownames_to_column("cell_type")%>%
  mutate(cell_type=factor(cell_type,levels=cell_type))%>%
  ggplot(aes(x=logFC,y=cell_type,fill=logFC,size=adj.P.Val))+geom_point(shape=21)+
  scale_size(range=c(8,1),breaks = c(0.5,0.05))+
  scale_fill_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  theme_classic(base_size = 14)+ggtitle("LA - no LA")

temp<-mesen%>%count(has_LA,published_mesenchymal_subtype,SampleName,name = "cell_n")%>%
    group_by(SampleName)%>%
    mutate(total=sum(cell_n),prop=100*cell_n/total)
temp<-temp%>%group_by(published_mesenchymal_subtype)%>%
  summarise(cell_n=sum(cell_n),has_LA="Total")%>%
  bind_rows(temp%>%mutate(has_LA=as.character(has_LA)))%>%
  mutate(published_mesenchymal_subtype=factor(published_mesenchymal_subtype,
                                              levels=res%>%arrange(logFC)%>%rownames()%>%rev()))

p0<-temp%>%ggplot(aes(y=cell_n,x=has_LA,fill=published_mesenchymal_subtype))+
  geom_bar(stat="identity",position = "fill")+
  scale_fill_manual(values=unique(c(kelly.colours)))#modified kelly.colours

#repeat for epi
epi<-aux_table%>%filter(Class=="Peritoneal endometriosis"&
                              !is.na(published_epithelial_subtype)&published_epithelial_subtype!="")

```

#more progeny plots
```{r}
sc<-readRDS("data/fixed_annotated_aux.seurat.rds")
sc<-subset(sc,cells = which(sc$Class=="Peritoneal endometriosis"))
progeny<-data.table::fread("data/progeney_scores.tsv")
progeny<-progeny%>%filter(Cell%in%colnames(sc))
progeny<-progeny[order(match(progeny$Cell,colnames(sc))),]
sc<-AddMetaData(sc,metadata = progeny,col.name = colnames(progeny)[-1])

p0<-DotPlot(subset(sc,cells = which(sc$has_LA==TRUE)),features = colnames(progeny)[-1])$data
p1<-DotPlot(subset(sc,cells = which(sc$has_LA==FALSE)),features = colnames(progeny)[-1])$data
temp<-p0%>%as.data.frame()%>%mutate(has_LA="T")%>%
  bind_rows(p1%>%as.data.frame()%>%mutate(has_LA="F"))
temp%>%ggplot(aes(x=has_LA,y=id,col=avg.exp.scaled,size=pct.exp))+geom_point()+facet_grid(~features.plot)+scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+theme_classic()+theme(strip.background = element_blank(),strip.text.x = element_text(angle=45))

temp<-aux_table%>%select(SampleName,harmonized_major_cell_type,has_LA,Androgen:WNT)
temp<-temp%>%group_by(SampleName,harmonized_major_cell_type,has_LA)%>%summarise(across(Androgen:WNT,mean))

```
```{r}
markers<-list("Immune regulation"=c("BSG","PDCD1","CD274","PDCD1LG2","TGFB1","IL10","EBI3","GZMB"),
            "Differentiation state"=c("CD80","CD86","CD27","CD38","CD24","CD69","CD70"),
            "GC vs non-GC"=c("BCL2","BCL6"),
            "B1 vs B2 vs Mz"= c("CR1","CR2","FCER2"),
            "CD22","CD19","MS4A1",
            Naive=c("IGHD","IGHM"))
markers<-markers%>%reshape2::melt()%>%mutate(marker=value)%>%select(-value)%>%deframe()

temp%>%ggplot(aes(x=has_LA,y=features.plot,size = pct.exp,colour = avg.exp.scaled,group = feature.groups))+geom_point()+scale_color_viridis_c(option = 'H')+facet_grid(cols=vars(id),rows = vars(feature.groups),scales = "free_y",space = "free")+theme_classic(base_size = 14)+theme(strip.text.x = element_text(angle = 55,vjust = .5,hjust = .5),strip.background = element_blank(),strip.text.y = element_text(angle = 0))+labs(x="has LA",y="",col="Average\nexpression",size="Percent\nexpressed")+ggtitle("Scaled per LA group")
```
#LA_bioinfo: 228
```{r}
sc<-subset(sc,cells = which(!is.na(sc$Final_Immune_Cluster_ID)))
markers<-list("B-cells"=c("MS4A1","CD19","IGHD","IGHM","BCL2","BCL6","CD24","CD27",
                          "CD38","SDC1","PRDM1","CD69","CD70","CD80","CD86"),
            "NK cells"=c("NCAM1","FCGR3A","NCR1","SPN","GZMA","PRF1","KLRD1","KIR3DL1"),
            "T-cells"=c("CD3D","TRAC","TRIB1","CD8A"),
            "CM/EM/RM"= c("SELL","CCR7","CD69","IL7R","CD44"),
            Exhausted=c("LAG3","PDCD1","CTLA4","TIGIT"),
            "Gamma-delta T-cells"=c("TRDC","TRGC1","KLRK1"),
            Th17=c("CD4","RORC","IL17A"),
            Th2=c("CD4","GATA3"),
            "Mast cells"=c("KIT","TPSAB1"),
            Myeloid=c("LYZ","PSAP"),
            DC=c("HLA-DQA1","CD74","FCER1A","CD1C","CLEC10A"),
            M1=c("CD36","S100A8","NOS2","CXCL10"),
            M2=c("IL10","VEGFA","CCL13","CCL20"),
            "checkpoint/Immune regulators"=c("CD274","PDCD1LG2","VSIR","IDO1"))
plots<-lapply(markers,function(x) 
  DotPlot(sc,features = x,group.by = "Final_Immune_Cluster_ID",split.by = "has_LA"))
names(plots)<-names(markers)
temp<-lapply(names(plots), function(x) plots[[x]]$data%>%mutate(phenotype=x))%>%bind_rows()
temp<-temp%>%mutate(celltype=str_remove(id,"_.+"),has_LA=str_remove(id,".+_"))
cellorder<-sc@meta.data%>%
  distinct(harmonized_major_plus_immune_cell_type,harmonized_major_cell_type)%>%
  mutate(harmonized_major_cell_type=ifelse(harmonized_major_plus_immune_cell_type=="Early Exhausted CD8 T-cells (2)","T cells",harmonized_major_cell_type))%>%
  arrange(harmonized_major_cell_type)
cellorder<-cellorder[c(1,9,2:8,10:nrow(cellorder)),]
temp<-temp%>%mutate(celltype=factor(celltype,levels=cellorder$harmonized_major_plus_immune_cell_type),
                    phenotype=factor(phenotype,levels=names(markers)))
temp%>%ggplot(aes(y=has_LA,x=features.plot,col=avg.exp,size=pct.exp))+geom_point()+facet_grid(cols=vars(phenotype),rows=vars(celltype),scales = "free",space = "free",switch = 'y')+scale_color_viridis_c(option = "H")+theme_light()+theme(strip.background = element_blank(),axis.text.x = element_text(angle=45,vjust = 1,hjust = 1),strip.text.y.left = element_text(angle = 0,colour = "black",vjust = .5,hjust = 1),strip.text.x = element_text(colour = "black"))+scale_y_discrete(position = "right")
```
# SCENIC plot
```{r}
b_scenic<-read_csv("int/bcells.auc.csv")
b_scenic<-aux_table%>%
  distinct(barcode,LA_per_Sample,Final_Immune_Cluster_ID)%>%
  right_join(b_scenic,by=c("barcode"="Cell"))
b_scenic$has_LA<-b_scenic$LA_per_Sample>0
scaled<-b_scenic%>%
  column_to_rownames("barcode")%>%
  select(`ARID3A(+)`:`ZSCAN18(+)`)%>%
  t()%>%scale()%>%t()
scaled<-scaled%>%as.data.frame()%>%
  rownames_to_column("barcode")%>%
  left_join(b_scenic%>%select(barcode,has_LA))
scaled<-scaled%>%
  pivot_longer(`ARID3A(+)`:`ZSCAN18(+)`,
               names_to = "regulon",values_to = "score")
scaled<-scaled%>%
  mutate(positiv=score>0)%>%
  group_by(has_LA,regulon)%>%
  summarise(score=mean(score),
         cells=sum(positiv>0))
scaled<-scaled%>%
  group_by(regulon)%>%
  mutate(type=ifelse(has_LA[which.max(score)],"LA+","LA-"),
         dif=max(score)-min(score))


scaled%>%group_by(type)%>%slice_max(abs(dif),n=20)%>%
  ggplot(aes(y=regulon,x=has_LA,col=score,size=prop))+geom_point()+
  facet_grid(rows=vars(type),scales = "free_y",space = "free")+
  scale_colour_viridis_c(option = "H")+theme(strip.background = element_blank())+labs(size="% positive")

regulons<-read_csv("int/bcells.regulons.csv")
i<-scaled%>%group_by(type)%>%slice_max(abs(dif),n=20)%>%ungroup()%>%filter(type=="LA+")%>%distinct(regulon)%>%unlist()
i<-str_remove(i,"\\(.+")
get_targets<-function(tf){
  regulons%>%filter(TF==tf)%>%
    select(TargetGenes)%>%unlist()%>%
    paste(collapse = ", ")%>%#if several motifs
    str_split_1(pattern = ", \\(")%>%
    str_remove_all("\\[|\\(|\\'|, .+")%>%
    unique()}
targets<-lapply(i, get_targets)
names(targes)<-i
DotPlot(subset(sc,cells = which(sc$harmonized_major_cell_type=="B cells")),features = targets$KLF6,group.by = "has_LA")+coord_flip()+scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+ggtitle("KLF6 regulon")
oraRes<-lapply(targets,function(x) enricher(x,TERM2GENE = m_df)%>%as.data.frame()%>%filter(Count>1))

```
# B cells
```{r}
sc<-subset(sc,cells = which(sc$harmonized_major_cell_type=="B cells"))
temp<-FetchData(sc,vars=c("IGHD","CD27"))
temp<-temp%>%mutate(subB=case_when(IGHD<0.9&CD27<0.5~"Double negative",IGHD>0.9&CD27<0.5~"Naive",IGHD<0.9&CD27>0.5~"Class switch memory and PB/PC",IGHD>0.9&CD27>0.5~"Non-class-switch memory"))

temp<-m_df%>%filter(str_detect(gs_name,"TOLL"))
temp<-split(temp,f = temp$gs_name)%>%lapply(function(x) x$gene_symbol)
sc<-AddModuleScore(sc,features = temp)
colnames(sc@meta.data)[173:175]<-names(temp)

p0<-DotPlot(sc,features = colnames(sc@meta.data)[c(173:175,177:179)],group.by = "subB",scale = F)+scale_color_viridis_c()+ggtitle("All 4 classes")+scale_size(range = c(3,6))+theme(axis.text.x = element_text(angle=90,vjust = 1,hjust = 1))
p1<-DotPlot(subset(sc,cells=which(sc$subB=="Double negative"&!is.na(sc$has_LA))),features = colnames(sc@meta.data)[c(173:175,177:179)],group.by = "has_LA",scale = F)+scale_color_viridis_c()+ggtitle("PE only")+scale_size(range = c(3,6))+theme(axis.text.x = element_text(angle=90,vjust = 1,hjust = 1))

```
