---
title: "sc_endo_mc"
author: "Na Jeong Kim"
date: '2023-05-18'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

library(Seurat)
library(tidyverse)
library(cowplot)
library(broom)
library(ggplot2)
library(dplyr)
library(reshape)
#library(clusterProfiler)
library(readxl)
library(ggrepel)
library(clustree)
library(pheatmap)
#library(sankeyNetwork)
```


```{r}
imm_cells <- readRDS("data/Immune_Cell_annotation.rds")
```

```{r}
#cluster.cols = c("#67001f", "#a50026", "#d73027", "#f46d43", "#fdae61", "#fee090", "#ffffbf", "#a6dba0", "#1a9850", "#e0f3f8", "#abd9e9")

plot_1 <- DimPlot(object = imm_cells, pt.size = 0.1, group.by ="Immune_Cluster_ID", label = T, raster=FALSE) +
  theme_classic(base_size = 20) ##this is a umap with the clusters grouped with their cell identity

plot_1
```

```{r}
# Pull out mast cell population from imm_cells
mc <- subset(imm_cells, subset = Immune_Cluster_ID %in% "Mast cells")

```

```{r}
# Mast cell numbers on surgical classification

prop.cells <- data.frame(table(mc@meta.data$Surgical.classification))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Mast Cells")

# Mast cell numbers on Major class

mc@meta.data <- droplevels(mc@meta.data)

prop.cells <- data.frame(table(mc@meta.data$Class))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_classic(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank()) +
  labs(y = "Number of Mast Cells")

# Mast cell numbers of LA status

prop.cells <- data.frame(table(mc@meta.data$LA_Status[mc@meta.data$Class == "Peritoneal endometriosis"]))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
prop.cells <- prop.cells%>%filter(Var1!="NA") #Removing NA in the column
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "Number of Mast Cells",
       x = "LA status")

# Mast cell numbers of Hormonal States

prop.cells <-  data.frame(table(mc@meta.data$Hormone_status[mc@meta.data$Class == "Peritoneal endometriosis"]))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(y = "Number of Mast Cells",
       x = "Hormone status")

# Mast cell numbers of Menstrual Cycle

prop.cells <- data.frame(table(mc@meta.data$Menstral_cycle[mc@meta.data$Class == "Peritoneal endometriosis"]))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(y = "Number of Mast Cells",
       x = "Menstral cycle")

# Mast cell numbers of KRAS Mutation

prop.cells <- data.frame(table(mc@meta.data$KRAS_Mut[mc@meta.data$Class == "Peritoneal endometriosis"]))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(y = "Number of Mast Cells",
       x = "KRAS Mutation status")

# Mast cell numbers of ARID1A Mutation

prop.cells <- data.frame(table(mc@meta.data$ARID1A_Mut[mc@meta.data$Class == "Peritoneal endometriosis"]))
prop.cells$Var1 <- factor(prop.cells$Var1, levels = prop.cells$Var1)
ggplot(prop.cells, aes(Var1, Freq)) +
  geom_col() +
  theme_minimal(base_size = 15) +
  geom_text(aes(label=Freq), position=position_dodge(width=0.9), vjust=-0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1))+
  labs(y = "Number of Mast Cells",
       x = "ARID1A Mutation status")
```

```{r}
#cell proportions by LA tissue activity

mc@meta.data <- droplevels(mc@meta.data)
counts.prop = data.frame(table(mc@meta.data$LA_Status, mc@meta.data$Immune_Cluster_ID))
counts.prop.perc = group_by(counts.prop, Var2) %>% mutate(percent = Freq/sum(Freq))
head(counts.prop.perc)
aux = aggregate(counts.prop$Freq, by=list(Category=counts.prop$Var1), FUN=sum)

colnames(aux) <- c("Var1", "Freq", "Var2")
aux$percent = aux$Freq / sum(aux$Freq)
counts.prop.perc = rbind(as.data.frame(counts.prop.perc), aux)
bsize = 20
p2 <- ggplot(counts.prop.perc, aes(x = Var2, y = percent, fill = Var1)) +
  geom_bar(position="stack",stat = "identity", width=0.8) +
  scale_fill_manual(name="LA Group", values = c("High" = "#FC8D59",
                                                    "Low" = "#91BFDB",
                                                  "Exclude" = "#8B0000",
                                                  "NA" = "#2F4F4F")) +
  scale_x_discrete(limits = rev(levels(counts.prop.perc$Var2))) +
  coord_flip() +
  theme_set(theme_classic(base_size = 30)) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 270, hjust = 1, color = "black"),
        axis.text.y = element_text(angle = 0, hjust = 1, color = "black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle('Proportion of Mast cells in LA Status') +
  theme_classic(base_size = 25)

p2

#cell proportions by Class

mc@meta.data <- droplevels(mc@meta.data)
counts.prop = data.frame(table(mc@meta.data$Class, mc@meta.data$Immune_Cluster_ID))
counts.prop.perc = group_by(counts.prop, Var2) %>% mutate(percent = Freq/sum(Freq))
head(counts.prop.perc)
aux = aggregate(counts.prop$Freq, by=list(Category=counts.prop$Var1), FUN=sum)

colnames(aux) <- c("Var1", "Freq", "Var2")
aux$percent = aux$Freq / sum(aux$Freq)
counts.prop.perc = rbind(as.data.frame(counts.prop.perc), aux)
bsize = 20
p3 <- ggplot(counts.prop.perc, aes(x = Var2, y = percent, fill = Var1)) +
  geom_bar(position="stack",stat = "identity", width=0.8) +
  scale_fill_manual(name="Class", values = c("Endometrioma" = "#7b3294", 
                      "Eutopic endometrium" = "#c2a5cf", 
                      "Peritoneal endometriosis" = "#d9f0d3", 
                      "Unaffected ovary" = "#008837")) +
  scale_x_discrete(limits = rev(levels(counts.prop.perc$Var2))) +
  coord_flip() +
  theme_set(theme_classic(base_size = 30)) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 270, hjust = 1, color = "black"),
        axis.text.y = element_text(angle = 0, hjust = 1, color = "black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle('Proportion of Mast cells in Disease Classes') +
  theme_classic(base_size = 25)

p3

# cell proportions by menstrual cycle phase (mast cells)


mc@meta.data <- droplevels(mc@meta.data)

counts.prop = data.frame(table(mc@meta.data$Menstral_cycle, mc@meta.data$Immune_Cluster_ID))
counts.prop.perc = group_by(counts.prop, Var2) %>% mutate(percent = Freq/sum(Freq))
head(counts.prop.perc)
aux = aggregate(counts.prop$Freq, by=list(Category=counts.prop$Var1), FUN=sum)
aux$Var2 = "Total"
colnames(aux) <- c("Var1", "Freq", "Var2")
aux$percent = aux$Freq / sum(aux$Freq)
counts.prop.perc = rbind(as.data.frame(counts.prop.perc), aux)

bsize = 20
p4 <- ggplot(counts.prop.perc, aes(x = Var2, y = percent, fill = Var1)) + 
  geom_bar(position="stack",stat = "identity", width=0.8) +
  scale_fill_manual(name="Menstrual cycle", values = c("Follicular" = "orange",
                                             "Luteal" = "red",
                                             "Hormone" = "blue")) +
  scale_x_discrete(limits = rev(levels(counts.prop.perc$Var2))) +
  coord_flip() +
  theme_set(theme_classic(base_size = 25)) +
  theme(plot.title = element_text(hjust = 0.3),
        axis.text.x = element_text(angle = 270, hjust = 1, color = "Black"),
        axis.text.y = element_text(angle = 0, hjust = 1, colour = "Black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle('Proportion of Mast cells in Menstrual cycle phase')

p4
```

```{r}
# cell proportions by menstrual cycle phase (all immune cells)
imm_cells@meta.data <- droplevels(imm_cells@meta.data)

counts.prop = data.frame(table(imm_cells@meta.data$Menstral_cycle, imm_cells@meta.data$Immune_Cluster_ID))
counts.prop.perc = group_by(counts.prop, Var2) %>% mutate(percent = Freq/sum(Freq))
head(counts.prop.perc)
aux = aggregate(counts.prop$Freq, by=list(Category=counts.prop$Var1), FUN=sum)
aux$Var2 = "Total"
colnames(aux) <- c("Var1", "Freq", "Var2")
aux$percent = aux$Freq / sum(aux$Freq)
counts.prop.perc = rbind(as.data.frame(counts.prop.perc), aux)

bsize = 20

p5 <- counts.prop.perc%>%filter(Var2%in%c("Mast cells","Total"))%>%mutate(Var3 = factor(Var2, levels = c("Mast cells", "Total")))%>%
  ggplot(aes(x = Var3, y = percent, fill = Var1)) + 
  geom_bar(position="stack",stat = "identity", width=0.8) +
  scale_fill_manual(name="Menstrual cycle", values = c("Follicular" = "orange",
                                             "Luteal" = "red",
                                             "Hormone" = "blue")) +
  scale_x_discrete(limits = rev(levels(counts.prop.perc$Var3))) +
  coord_flip() +
  theme_set(theme_classic(base_size = 10)) +
  theme(plot.title = element_text(hjust = 0.3),
        axis.text.x = element_text(angle = 270, hjust = 1, color = "Black"),
        axis.text.y = element_text(angle = 0, hjust = 1, colour = "Black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle('Proportion of Mast cells in Menstrual cycle phase')

p5
```

```{r}
imm_cells@meta.data <- droplevels(imm_cells@meta.data)

counts.prop = data.frame(table(imm_cells@meta.data$KRAS_Mut, imm_cells@meta.data$Immune_Cluster_ID))
counts.prop.perc = group_by(counts.prop, Var2) %>% mutate(percent = Freq/sum(Freq))
head(counts.prop.perc)
aux = aggregate(counts.prop$Freq, by=list(Category=counts.prop$Var1), FUN=sum)
aux$Var2 = "Total"
colnames(aux) <- c("Var1", "Freq", "Var2")
aux$percent = aux$Freq / sum(aux$Freq)
counts.prop.perc = rbind(as.data.frame(counts.prop.perc), aux)

bsize = 20

p5.1 <- counts.prop.perc%>%filter(Var2%in%c("Mast cells","Total"))%>%mutate(Var3 = factor(Var2, levels = c("Mast cells", "Total")))%>%
  ggplot(aes(x = Var3, y = percent, fill = Var1)) + 
  geom_bar(position="stack",stat = "identity", width=0.8) +
  scale_fill_viridis_d() +
  scale_x_discrete(limits = rev(levels(counts.prop.perc$Var3))) +
  coord_flip() +
  theme_set(theme_classic(base_size = 20)) +
  theme(plot.title = element_text(hjust = 0.3),
        axis.text.x = element_text(angle = 270, hjust = 1, color = "Black"),
        axis.text.y = element_text(angle = 0, hjust = 1, colour = "Black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle('Proportion of Mast cells in KRAS Mutation Status')

p5.1
```


```{r}
# cell proportions by LA status (total immune cells and mast cells separately)

data.frame(table(mc@meta.data$KRAS_Mut[mc@meta.data$Class == "Peritoneal endometriosis"]))

imm_cells@meta.data <- droplevels(imm_cells@meta.data)

counts.prop = data.frame(table(imm_cells@meta.data$LA_Status, imm_cells@meta.data$Immune_Cluster_ID))
counts.prop.perc = group_by(counts.prop, Var2) %>% mutate(percent = Freq/sum(Freq))
head(counts.prop.perc)
aux = aggregate(counts.prop$Freq, by=list(Category=counts.prop$Var1), FUN=sum)
aux$Var2 = "Total"
colnames(aux) <- c("Var1", "Freq", "Var2")
aux$percent = aux$Freq / sum(aux$Freq)
counts.prop.perc = rbind(as.data.frame(counts.prop.perc), aux)

bsize = 20

p6 <- counts.prop.perc%>%filter(Var2%in%c("Mast cells","Total"))%>%mutate(Var3 = factor(Var2, levels = c("Mast cells", "Total")))%>%
  ggplot(aes(x = Var3, y = percent, fill = Var1)) +
  geom_bar(position="stack",stat = "identity", width=0.8) +
  scale_fill_manual(name="LA Group", values = c("High" = "#FC8D59",
                                                    "Low" = "#91BFDB",
                                                  "Exclude" = "#8B0000",
                                                  "NA" = "#2F4F4F")) +
  scale_x_discrete(limits = rev(levels(counts.prop.perc$Var3))) +
  coord_flip() +
  theme_set(theme_classic(base_size = 30)) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 270, hjust = 1, color = "black"),
        axis.text.y = element_text(angle = 0, hjust = 1, color = "black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle('Proportion of Mast cells in LA Status') +
  theme_classic(base_size = 25)

p6

```

```{r}
# cell proportions by Hormonal status (total immune cells and mast cells separately)

imm_cells@meta.data <- droplevels(imm_cells@meta.data)

counts.prop = data.frame(table(imm_cells@meta.data$Hormone_status, imm_cells@meta.data$Immune_Cluster_ID))
counts.prop.perc = group_by(counts.prop, Var2) %>% mutate(percent = Freq/sum(Freq))
head(counts.prop.perc)
aux = aggregate(counts.prop$Freq, by=list(Category=counts.prop$Var1), FUN=sum)
aux$Var2 = "Total"
colnames(aux) <- c("Var1", "Freq", "Var2")
aux$percent = aux$Freq / sum(aux$Freq)
counts.prop.perc = rbind(as.data.frame(counts.prop.perc), aux)

bsize = 20

p7 <- counts.prop.perc%>%filter(Var2%in%c("Mast cells","Total"))%>%mutate(Var3 = factor(Var2, levels = c("Mast cells", "Total")))%>%
  ggplot(aes(x = Var3, y = percent, fill = Var1)) +
  geom_bar(position="stack",stat = "identity", width=0.8) +
  scale_fill_manual(name="Hormonal States", values = c("No" = "#FC8D59",
                                                    "Yes" = "#91BFDB")) +
  scale_x_discrete(limits = rev(levels(counts.prop.perc$Var3))) +
  coord_flip() +
  theme_set(theme_classic(base_size = 30)) +
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 270, hjust = 1, color = "black"),
        axis.text.y = element_text(angle = 0, hjust = 1, color = "black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle('Proportion of Mast cells in Hormonal states') +
  theme_classic(base_size = 25)

p7

```

```{r}
# cell proportions by Mutation  (total immune cells and mast cells separately)

imm_cells@meta.data <- droplevels(imm_cells@meta.data)

counts.prop = data.frame(table(imm_cells@meta.data$ARID1A_Mut, imm_cells@meta.data$Immune_Cluster_ID))
counts.prop.perc = group_by(counts.prop, Var2) %>% mutate(percent = Freq/sum(Freq))
head(counts.prop.perc)
aux = aggregate(counts.prop$Freq, by=list(Category=counts.prop$Var1), FUN=sum)
aux$Var2 = "Total"
colnames(aux) <- c("Var1", "Freq", "Var2")
aux$percent = aux$Freq / sum(aux$Freq)
counts.prop.perc = rbind(as.data.frame(counts.prop.perc), aux)
bsize = 20

p8 <- counts.prop.perc%>%
  filter(Var2%in%c("Mast cells","Total"))%>% 
  mutate(Var3 = factor(Var2, levels = c("Mast cells", "Total")))%>%
  ggplot(aes(x = Var3, y = percent, fill = Var1)) +
  geom_bar(position="stack",stat = "identity", width=0.8) +
  # scale_fill_discrete(name="ARID1A Mutation Status")+
    scale_fill_viridis_d(name="ARID1A Mutation Status")+
  # scale_fill_manual(name="ARID1A Mutation Status", values = c("Heterogenous" = "red",
  #                                                   "NP" = "green",
  #                                                   "NP|Positive" = "blue",
  #                                                   "Positive" = "orange")) +
  scale_x_discrete(limits = rev(levels(counts.prop.perc$Var3))) +
  coord_flip() +
  theme_classic(base_size = 10)+
  theme(plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(angle = 270, hjust = 1, color = "black"),
        axis.text.y = element_text(angle = 0, hjust = 1, color = "black"),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle('Proportion of Mast cells in ARID1A Mutation Status')

p8
```

```{r}
# Reproduce p8 with tidyverse style (above)
plot_df <- imm_cells@meta.data%>% 
  group_by(ARID1A_Mut, Immune_Cluster_ID) %>%
  summarise(freq=n()) %>%
  group_by(ARID1A_Mut)%>%
  summarise(freq=sum(freq))%>%
  bind_rows(plot_df)%>%
  mutate(ARID1A_Mut=replace_na(ARID1A_Mut,"Total"))

view(plot_df)

  mutate(freq,prop= freq/sum(freq)) %>%
  aggregate(plot_df$freq, by=list(Category=plot_df$ARID1A_Mut))%>%
  filter(Immune_Cluster_ID %in%c("Total", "Mast cells"))

p9 <- plot_df%>%
  ggplot(aes(y=Immune_Cluster_ID, x=freq, fill=ARID1A_Mut))+
  labs(y="ARID1A", x="")+
  geom_bar(stat="identity", position = "fill")

p9

```


```{r}
# Looking at markers on mast cells in the group of peritoneal endometriosis based on LA status

mc_2 <- subset(mc, subset = Class %in% "Peritoneal endometriosis")

DotPlot(mc_2, group.by = "LA_Status", features = c("CD69", "LIF", "NAMPT", "NCL")) + 
  theme_classic(base_size = 20) +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.8, hjust = 0.5, color = "black"), axis.text.y = element_text(size = 20, colour = "black")) +
  coord_flip() +
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  labs(x = "",
       y = "LA Status")

```

```{r}
# Looking at mast cell Markers on mast cell population

DotPlot(mc, group.by = "Class", features = c("KIT","KITLG", "CCL2", "VCAM1", "CPA3", "TPSAB1", "TNF", "FGFR1", "CMA1", "CCR1", "IL1B", "IL3", "ESR1", "ESR2", "PGR", "MCEMP1", "IGHE", "FCER1A", "FGF2", "CCR3")) +theme_classic(base_size = 20) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.8, hjust = 0.5, size = 10, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) +
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  labs(x = "",
       y = "")

# By hormonal state

DotPlot(mc_2, group.by = "Hormone_status", features = c("KIT","KITLG", "CCL2", "VCAM1", "CPA3", "TPSAB1", "TNF", "FGFR1", "CMA1", "CCR1", "IL1B", "IL3", "ESR1", "ESR2", "PGR", "MCEMP1", "IGHE", "FCER1A", "FGF2", "CCR3")) +theme_classic(base_size = 20) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.8, hjust = 0.5, size = 10, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) +
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")

# By menstrual cycle
DotPlot(mc, group.by = "Menstral_cycle", features = c("KIT","KITLG", "CCL2", "VCAM1", "CPA3", "TPSAB1", "TNF", "FGFR1", "CMA1", "CCR1", "IL1B", "IL3", "ESR1", "ESR2", "PGR", "MCEMP1", "IGHE", "FCER1A", "FGF2", "CCR3")) +theme_classic(base_size = 20) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.8, hjust = 0.5, size = 10, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) +
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")

#By LA status
DotPlot(mc_2, group.by = "LA_Status", features = c("KIT","KITLG", "CCL2", "VCAM1", "CPA3", "TPSAB1", "TNF", "FGFR1", "CMA1", "CCR1", "IL1B", "IL3", "ESR1", "ESR2", "PGR", "MCEMP1", "IGHE", "FCER1A", "FGF2", "CCR3")) +theme_classic(base_size = 20) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.8, hjust = 0.5, size = 10, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) +
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+
   labs(x = "",
       y = "")
```

```{r}
# Mast cell target markers LA hi vs lo (peritoneal endometriosis)

DotPlot(mc_2, group.by = "LA_Status", features = c("IL4", "IL13", "IL4R", "SIGLEC8", "NFKB1", "PPP3CA", "STAT5A", "STAT5B", "STAT3", "STAT6", "JAK1", "JAK3", "JAK2", "DRD1", "DRD2", "RRARG", "LYN", "FYN", "SYK", "PIK3CB", "PIK3CA", "MTOR", "BTK", "KRAS", "MRGPRX2", "AKT1", "AKT2", "AKT3")) +theme_classic(base_size = 15) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.8, hjust = 0.5, size = 10, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) +
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+
   labs(x = "",
       y = "LA Status")
```


```{r}
# Differential Gene Expression between Peritoneal Endometriosis vs Eutopic Endometrium on mast cells subset

Idents(object = mc) <- mc@meta.data$Major.Class

DEG.res <- FindAllMarkers(mc, test.use = "MAST")

DEG.res2 <- FindMarkers(mc, ident.1 = "Peritoneal Endometriosis", ident.2 = "Eutopic Endometrium", test.use = "MAST")

fc.p = 1.1
pv.p = 0.05
DEG.res$STATUS = "NOT.SIG"
DEG.res[DEG.res$avg_log2FC < -fc.p & DEG.res$p_val_adj < pv.p, ]$STATUS = "Down"
DEG.res[DEG.res$avg_log2FC > fc.p & DEG.res$p_val_adj < pv.p, ]$STATUS = "Up"

feature = "Surgical"
c = "Deep"

markers.filt = DEG.res[DEG.res$cluster == c,]
nDEG = nrow(markers.filt)
genes = markers.filt$gene[markers.filt$cluster == c & markers.filt$STATUS != "NOT.SIG"]

```

```{r}

sel.mc = subset(mc, subset = Major.Class %in% "Endometriosis")

Idents(object = sel.mc) <- sel.mc@meta.data$LA_Status

DEG.res <- FindAllMarkers(sel.mc, test.use = "MAST")

p.v = 0.05
fc = 0.5

DEG.res$STATUS = "NOT.SIG"
DEG.res[DEG.res$avg_log2FC < -fc & DEG.res$p_val_adj < p.v, ]$STATUS = "Down"
DEG.res[DEG.res$avg_log2FC > fc & DEG.res$p_val_adj < p.v, ]$STATUS = "Up"

features.deg = NULL
for (o in unique(DEG.res$cluster)) {
  features.deg = c(features.deg, head(DEG.res$gene[DEG.res$cluster == o  & DEG.res$STATUS == "Up"], 10))
}


pd <- DotPlot(sel.mc, features = unique(features.deg)) +
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b") +
  coord_flip() +
  RotatedAxis()
pd
```

```{r}
# put DEG list into csv
write_csv(DEG.res,"data/DEG_LA_mc.csv")
```

```{r}
# with more mast cell markers (therapeutic targets for mast cells)

DotPlot(mc, group.by = "Class", features = c("IL4", "IL13", "IL4R", "SIGLEC8", "NFKB1", "PPP3CA", "STAT5A", "STAT5B", "STAT3", "STAT6", "JAK1", "JAK3", "JAK2", "DRD1", "DRD2", "RRARG", "LYN", "FYN", "SYK", "PIK3CB", "PIK3CA", "MTOR", "BTK", "KRAS", "MRGPRX2", "AKT1", "AKT2", "AKT3")) +theme_classic(base_size = 15) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.8, hjust = 0.5, size = 10, colour = "black"), axis.text.y = element_text(size = 10, colour = "black")) +
  scale_colour_gradient2(low = "#2166ac", mid = "#f7f7f7", high = "#b2182b")+
  labs(x = "",
       y = "")
```

```{r}
library(biomaRt)
library(clusterProfiler)
library(ReactomePA)
```

