```{r}
library(Seurat)
library(tidyverse)
library(ggrepel)
library(msigdbr)
library(clusterProfiler)

sc<-readRDS("data/fixed_annotated_aux.seurat.rds")#already has LA_perSample column in metadata
sc<-subset(sc,cells = which(sc$Class=="Peritoneal endometriosis"))
sc$has_LA<-sc$LA_per_Sample>0
```
# Get subsets of interest
I'm changing epithelial_subcluster_type/mesenchymal_subcluster_type for harmonized
because harmonized is my base for all plots and they differe in 2/11 cells respectively
```{r}
enepi<-subset(sc,
              cells=which(sc$harmonized_major_cell_type=="EnEpi cells"&
                            !is.na(sc$published_epithelial_subtype)))
Idents(enepi)<-enepi$has_LA
#single cell test
deg_enepi<-FindMarkers(enepi,ident.1 = "TRUE",test.use="MAST")

ens<-subset(sc,
              cells=which(sc$harmonized_major_cell_type== "EnS cells"&
                            !is.na(sc$published_mesenchymal_subtype)))
Idents(ens)<-ens$has_LA
deg_ens<-FindMarkers(ens,ident.1 = "TRUE",test.use="MAST")

```
# DESeq2 DEG
```{r}
enepi_bulk<-AggregateExpression(
  enepi,
  assays = "RNA",
  return.seurat = T,
  group.by = "SampleName")
temp<-enepi@meta.data%>%distinct(SampleName,has_LA)%>%
  mutate(SampleName=str_replace(SampleName,"_","-"))
temp<-temp[order(match(temp$SampleName,colnames(enepi_bulk))),]
enepi_bulk<-AddMetaData(enepi_bulk,metadata = temp,col.name = "has_LA")
Idents(enepi_bulk)<-enepi_bulk$has_LA
deg <- FindMarkers(object = enepi_bulk, 
                         ident.1 = "TRUE", 
                         ident.2 = "FALSE",
                         test.use = "DESeq2")

ens_bulk<-AggregateExpression(
  ens,
  assays = "RNA",
  return.seurat = T,
  group.by = "SampleName")
temp<-ens@meta.data%>%distinct(SampleName,has_LA)%>%
  mutate(SampleName=str_replace(SampleName,"_","-"))
temp<-temp[order(match(temp$SampleName,colnames(ens_bulk))),]
ens_bulk<-AddMetaData(ens_bulk,metadata = temp,col.name = "has_LA")
Idents(ens_bulk)<-ens_bulk$has_LA
deg <- FindMarkers(object = ens_bulk, 
                         ident.1 = "TRUE", 
                         ident.2 = "FALSE",
                         test.use = "DESeq2")

```
# LIMMA DEG
```{r}
temp<-enepi@meta.data%>%distinct(SampleName,Patient.No.)%>%
  mutate(SampleName=str_replace(SampleName,"_","-"))%>%
  right_join(temp)
mat<-enepi_bulk@assays$RNA$counts
mat<-mat[,temp$SampleName]
temp$Patient.No.<-as.factor(temp$Patient.No.)
designM<-model.matrix(~0+has_LA+Patient.No.,#groups around replicates=samplename
                      data=temp)#
fit<-lmFit(log2(mat+0.01),designM)
cont<-makeContrasts(has_LATRUE-has_LAFALSE,levels = designM)
fit<-contrasts.fit(fit,cont)
fit <- eBayes(fit, robust=TRUE)
degLimma<-topTable(fit,number = nrow(mat))
```
#Intersection?
```{r}
i<-deg_enepi%>%filter(p_val_adj<0.05)%>%rownames()
j<-degLimma%>%filter(adj.P.Val<0.05)%>%rownames()
intersect(i,j)
```
# Plots
```{r}
deg_enepi<-deg_enepi%>%rownames_to_column("gene")%>%
  mutate(STATUS=case_when(p_val_adj<0.01&avg_log2FC<=-1~"Down",
                          p_val_adj<0.01&avg_log2FC>=1~"Up",
                          TRUE~"Not.Sig"))
deg_enepi%>%ggplot(aes(x=avg_log2FC,y=-log10(p_val_adj),col=STATUS))+geom_point()+
  geom_text_repel(data = deg_enepi%>%filter(STATUS!="Not.Sig"),
                  aes(x=avg_log2FC,y=-log10(p_val_adj),col=STATUS,label = gene),show.legend = F)+
  scale_color_manual(values = c("darkgreen", "grey", "red"))+
  theme_bw(base_size = 14)+
  theme(legend.position = "bottom")+
  ggtitle("EnEpi has LA - no LA, MAST test, abs LFC >= 1, p-val < 0.01: 35 Down, 120 Up")

degLimma<-degLimma%>%rownames_to_column("gene")%>%
    mutate(STATUS=case_when(adj.P.Val<0.01&logFC<=-1~"Down",
                            adj.P.Val<0.01&logFC>=1~"Up",
                            TRUE~"Not.Sig"))

```

# Enrichment
```{r}
m_df <- msigdbr(species = "Homo sapiens")%>%
    filter(str_detect(gs_name,"REACTOME"))%>%
    distinct(gs_name,gene_symbol)
temp<-deg_enepi%>%mutate(cell="EnEpi")%>%
  bind_rows(deg_ens%>%mutate(cell="EnS"))
temp<-temp%>%filter(STATUS!="Not.Sig")%>%unite("cl",cell:STATUS)
oraRes<-temp%>%split(temp$cl)%>%lapply(function(x) enricher(x$gene,TERM2GENE = m_df))
oraRes<-lapply(names(oraRes),function(x)
  oraRes[[x]]%>%as.data.frame()%>%mutate(cl=x))%>%bind_rows()

#TF enrichment?
hormo_targets<-list.files("docs",full.names = T)
hormo_targets<-hormo_targets[str_detect(hormo_targets,"targets")]
hormo_targets<-lapply(hormo_targets,function(x) 
  x%>%select(Name.TF,Name.Target))%>%bind_rows()
oraRes<-temp%>%split(temp$cl)%>%lapply(function(x)
  enricher(x$gene,TERM2GENE = hormo_targets,maxGSSize = 100000))
oraRes<-lapply(names(oraRes),function(x)
    oraRes[[x]]%>%as.data.frame()%>%mutate(cl=x))%>%bind_rows()
rownames(oraRes)<-NULL
oraRes<-oraRes%>%
  left_join(temp%>%count(cl,name = "total"))%>%
  mutate(prop=Count*100/total)
```
# try with cell clusters > 100 cells per LA status
```{r}
i<-sc@meta.data%>%
  count(has_LA,harmonized_major_plus_immune_cell_type,name = "cells_LA")%>%
  filter(cells_LA>100)%>%
  add_count(harmonized_major_plus_immune_cell_type)%>%
  filter(n==2)%>%
  distinct(harmonized_major_plus_immune_cell_type)%>%unlist()
i<-i[!i%in%c("EnEpi cells","EnS cells","Erythrocytes")]

Idents(sc)<-sc$has_LA
sc<-lapply(i, function(x) 
  subset(sc,cells = which(sc$harmonized_major_plus_immune_cell_type==x)))
deg<-lapply(sc,function(x) 
  FindMarkers(x,ident.1 = "TRUE",test.use="MAST",min.pct=0.1))
deg<-lapply(names(deg), function(x)
  deg[[x]]%>%as.data.frame()%>%rownames_to_column("gene")%>%
    mutate(cell=x))%>%bind_rows()
deg<-deg%>%
  mutate(STATUS=case_when(p_val_adj<0.01&avg_log2FC<=-1~"Down",
                          p_val_adj<0.01&avg_log2FC>=1~"Up",
                          TRUE~"Not.Sig"))

deg%>%ggplot(aes(x=avg_log2FC,y=-log10(p_val_adj),col=STATUS))+geom_point()+
    geom_text_repel(data = deg%>%filter(STATUS!="Not.Sig"),
                    aes(x=avg_log2FC,y=-log10(p_val_adj),
                        col=STATUS,label = gene),show.legend = F)+
    scale_color_manual(values = c("darkgreen", "grey", "red"))+
    theme_bw(base_size = 14)+
    theme(legend.position = "bottom")+facet_wrap(~cell,scales = "free")

temp<-deg%>%filter(STATUS!="Not.Sig")%>%unite("cl",cell:STATUS)
oraRes<-temp%>%split(temp$cl)%>%lapply(function(x) enricher(x$gene,TERM2GENE = m_df))
oraRes<-lapply(names(oraRes),function(x)
  oraRes[[x]]%>%as.data.frame()%>%mutate(cl=x))%>%bind_rows()
oraRes<-oraRes%>%separate(cl,into = c("cell","STATUS"),sep = "_")
```